[workspace]
members = [
    "crates/*",
]

# Enable for more accurate flamegraphs
[profile.release]
debug = 1
debug-assertions = true

[profile.dev.package.rapier3d]
opt-level = 3

[package]
name = "gauntlet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
mio = { version = "0.8.10", features = ["os-poll", "net"] }
hecs = "0.10.4"

graphite_concierge = { path = "./crates/graphite_concierge" }
graphite_network = { path = "./crates/graphite_network" }
graphite_core_server = { path = "./crates/graphite_core_server" }
graphite_mc_constants = { path = "./crates/graphite_mc_constants" }
graphite_mc_protocol = { path = "./crates/graphite_mc_protocol" }
graphite_anvil = { path = "./crates/graphite_anvil" }
graphite_entity = { path = "./crates/graphite_entity" }
graphite_binary = { path = "./crates/graphite_binary" }
graphite_pathfinding = { path = "./crates/graphite_pathfinding" }
graphite_goal_ai = { path = "./crates/graphite_goal_ai" }
graphite_command = { path = "./crates/graphite_command" }
enum_dispatch = "0.3.12"
glam = "0.25.0"
include_dir = "0.7.3"
rand = "0.8.5"
parry3d = "0.13.6"
rapier3d = "0.18.0"
once_cell = "1.19.0"
thiserror = "1.0.60"
strum_macros = "0.26.2"
strum = "0.26.2"
const_format = "0.2.32"
enumset = "1.1.5"
serde = "1.0.203"
serde_json = "1.0.117"
enum-map = "2.7.3"
sprintf = "0.3.1"
slab = "0.4.9"
tokio-postgres = { version = "0.7.12", features = ["with-uuid-1", "with-bit-vec-0_6", "with-serde_json-1"] }
postgres-protocol = "0.6.8"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread"] }
deadpool-postgres = "0.14.1"
uuid = "1.10.0"
chrono = "0.4.26"
num_enum = "0.5.7"
ctrlc = { version = "3.4", features = ["termination"] }
bit-vec = "0.6.3"
futures-util = "0.3.31"
bytes = "1.8.0"
rustc-hash = "1.1.0"
byteorder = "1.5.0"
