// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs
// Data is provided courtesy of `https://github.com/Minestom/MinestomDataGenerator`

use crate::block_parameter::*;

include!(concat!(env!("OUT_DIR"), "/block_to_u16.rs"));
include!(concat!(env!("OUT_DIR"), "/string_to_u16.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_block.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_item.rs"));
include!(concat!(env!("OUT_DIR"), "/set_block_property.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_block_attributes.rs"));

pub fn state_to_item(id: u16) -> Result<crate::item::Item, NoSuchBlockError> {
	if id >= ITEM_LUT.len() as _ { return Err(NoSuchBlockError(id)); }
	Ok(ITEM_LUT[id as usize])
}

pub fn string_to_u16(string: &str) -> Option<u16> {
	STRING_TO_U16.get(string).copied()
}

#[derive(Debug)]
pub struct BlockAttributes {
	pub hardness: f32,
	pub replaceable: bool,
	pub air: bool,
	pub is_north_face_sturdy: bool,
	pub is_east_face_sturdy: bool,
	pub is_south_face_sturdy: bool,
	pub is_west_face_sturdy: bool,
	pub is_up_face_sturdy: bool,
}

#[derive(Debug, thiserror::Error)]
#[error("No block exists for id: {0}")]
pub struct NoSuchBlockError(u16);

#[derive(Debug, Copy, Clone)]
pub enum Block {
	AcaciaButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	AcaciaDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	AcaciaFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	AcaciaFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	AcaciaHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	AcaciaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	AcaciaLog {
		axis: Axis3D,
	},
	AcaciaPlanks,
	AcaciaPressurePlate {
		powered: bool,
	},
	AcaciaSapling {
		stage: u8,
	},
	AcaciaSign {
		rotation: u8,
		waterlogged: bool,
	},
	AcaciaSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	AcaciaStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	AcaciaTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	AcaciaWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	AcaciaWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	AcaciaWood {
		axis: Axis3D,
	},
	ActivatorRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	Air,
	Allium,
	AmethystBlock,
	AmethystCluster {
		facing: Facing,
		waterlogged: bool,
	},
	AncientDebris,
	Andesite,
	AndesiteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	AndesiteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	AndesiteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Anvil {
		facing: Direction,
	},
	AttachedMelonStem {
		facing: Direction,
	},
	AttachedPumpkinStem {
		facing: Direction,
	},
	Azalea,
	AzaleaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	AzureBluet,
	Bamboo {
		age: u8,
		leaves: Leaves,
		stage: u8,
	},
	BambooBlock {
		axis: Axis3D,
	},
	BambooButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	BambooDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	BambooFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BambooFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	BambooHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	BambooMosaic,
	BambooMosaicSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BambooMosaicStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BambooPlanks,
	BambooPressurePlate {
		powered: bool,
	},
	BambooSapling,
	BambooSign {
		rotation: u8,
		waterlogged: bool,
	},
	BambooSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BambooStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BambooTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	BambooWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	BambooWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	Barrel {
		facing: Facing,
		open: bool,
	},
	Barrier {
		waterlogged: bool,
	},
	Basalt {
		axis: Axis3D,
	},
	Beacon,
	Bedrock,
	BeeNest {
		facing: Direction,
		honey_level: u8,
	},
	Beehive {
		facing: Direction,
		honey_level: u8,
	},
	Beetroots {
		age: u8,
	},
	Bell {
		attachment: Attachment,
		facing: Direction,
		powered: bool,
	},
	BigDripleaf {
		facing: Direction,
		tilt: Tilt,
		waterlogged: bool,
	},
	BigDripleafStem {
		facing: Direction,
		waterlogged: bool,
	},
	BirchButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	BirchDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	BirchFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BirchFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	BirchHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	BirchLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	BirchLog {
		axis: Axis3D,
	},
	BirchPlanks,
	BirchPressurePlate {
		powered: bool,
	},
	BirchSapling {
		stage: u8,
	},
	BirchSign {
		rotation: u8,
		waterlogged: bool,
	},
	BirchSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BirchStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BirchTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	BirchWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	BirchWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	BirchWood {
		axis: Axis3D,
	},
	BlackBanner {
		rotation: u8,
	},
	BlackBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BlackCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BlackCandleCake {
		lit: bool,
	},
	BlackCarpet,
	BlackConcrete,
	BlackConcretePowder,
	BlackGlazedTerracotta {
		facing: Direction,
	},
	BlackShulkerBox {
		facing: Facing,
	},
	BlackStainedGlass,
	BlackStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BlackTerracotta,
	BlackWallBanner {
		facing: Direction,
	},
	BlackWool,
	Blackstone,
	BlackstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BlackstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BlackstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	BlastFurnace {
		facing: Direction,
		lit: bool,
	},
	BlueBanner {
		rotation: u8,
	},
	BlueBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BlueCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BlueCandleCake {
		lit: bool,
	},
	BlueCarpet,
	BlueConcrete,
	BlueConcretePowder,
	BlueGlazedTerracotta {
		facing: Direction,
	},
	BlueIce,
	BlueOrchid,
	BlueShulkerBox {
		facing: Facing,
	},
	BlueStainedGlass,
	BlueStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BlueTerracotta,
	BlueWallBanner {
		facing: Direction,
	},
	BlueWool,
	BoneBlock {
		axis: Axis3D,
	},
	Bookshelf,
	BrainCoral {
		waterlogged: bool,
	},
	BrainCoralBlock,
	BrainCoralFan {
		waterlogged: bool,
	},
	BrainCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	BrewingStand {
		has_bottle_0: bool,
		has_bottle_1: bool,
		has_bottle_2: bool,
	},
	BrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Bricks,
	BrownBanner {
		rotation: u8,
	},
	BrownBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BrownCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BrownCandleCake {
		lit: bool,
	},
	BrownCarpet,
	BrownConcrete,
	BrownConcretePowder,
	BrownGlazedTerracotta {
		facing: Direction,
	},
	BrownMushroom,
	BrownMushroomBlock {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	BrownShulkerBox {
		facing: Facing,
	},
	BrownStainedGlass,
	BrownStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BrownTerracotta,
	BrownWallBanner {
		facing: Direction,
	},
	BrownWool,
	BubbleColumn {
		drag: bool,
	},
	BubbleCoral {
		waterlogged: bool,
	},
	BubbleCoralBlock,
	BubbleCoralFan {
		waterlogged: bool,
	},
	BubbleCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	BuddingAmethyst,
	Cactus {
		age: u8,
	},
	Cake {
		bites: u8,
	},
	Calcite,
	CalibratedSculkSensor {
		facing: Direction,
		power: u8,
		sculk_sensor_phase: SculkSensorPhase,
		waterlogged: bool,
	},
	Campfire {
		facing: Direction,
		lit: bool,
		signal_fire: bool,
		waterlogged: bool,
	},
	Candle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	CandleCake {
		lit: bool,
	},
	Carrots {
		age: u8,
	},
	CartographyTable,
	CarvedPumpkin {
		facing: Direction,
	},
	Cauldron,
	CaveAir,
	CaveVines {
		age: u8,
		berries: bool,
	},
	CaveVinesPlant {
		berries: bool,
	},
	Chain {
		axis: Axis3D,
		waterlogged: bool,
	},
	ChainCommandBlock {
		conditional: bool,
		facing: Facing,
	},
	CherryButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	CherryDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	CherryFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	CherryFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	CherryHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	CherryLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	CherryLog {
		axis: Axis3D,
	},
	CherryPlanks,
	CherryPressurePlate {
		powered: bool,
	},
	CherrySapling {
		stage: u8,
	},
	CherrySign {
		rotation: u8,
		waterlogged: bool,
	},
	CherrySlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CherryStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CherryTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	CherryWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	CherryWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	CherryWood {
		axis: Axis3D,
	},
	Chest {
		block_type: ChestType,
		facing: Direction,
		waterlogged: bool,
	},
	ChippedAnvil {
		facing: Direction,
	},
	ChiseledBookshelf {
		facing: Direction,
		slot_0_occupied: bool,
		slot_1_occupied: bool,
		slot_2_occupied: bool,
		slot_3_occupied: bool,
		slot_4_occupied: bool,
		slot_5_occupied: bool,
	},
	ChiseledCopper,
	ChiseledDeepslate,
	ChiseledNetherBricks,
	ChiseledPolishedBlackstone,
	ChiseledQuartzBlock,
	ChiseledRedSandstone,
	ChiseledSandstone,
	ChiseledStoneBricks,
	ChiseledTuff,
	ChiseledTuffBricks,
	ChorusFlower {
		age: u8,
	},
	ChorusPlant {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	Clay,
	CoalBlock,
	CoalOre,
	CoarseDirt,
	CobbledDeepslate,
	CobbledDeepslateSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CobbledDeepslateStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CobbledDeepslateWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Cobblestone,
	CobblestoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CobblestoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CobblestoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Cobweb,
	Cocoa {
		age: u8,
		facing: Direction,
	},
	CommandBlock {
		conditional: bool,
		facing: Facing,
	},
	Comparator {
		facing: Direction,
		mode: ComparatorMode,
		powered: bool,
	},
	Composter {
		level: u8,
	},
	Conduit {
		waterlogged: bool,
	},
	CopperBlock,
	CopperBulb {
		lit: bool,
		powered: bool,
	},
	CopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	CopperGrate {
		waterlogged: bool,
	},
	CopperOre,
	CopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	Cornflower,
	CrackedDeepslateBricks,
	CrackedDeepslateTiles,
	CrackedNetherBricks,
	CrackedPolishedBlackstoneBricks,
	CrackedStoneBricks,
	Crafter {
		crafting: bool,
		orientation: Orientation,
		triggered: bool,
	},
	CraftingTable,
	CreeperHead {
		powered: bool,
		rotation: u8,
	},
	CreeperWallHead {
		facing: Direction,
		powered: bool,
	},
	CrimsonButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	CrimsonDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	CrimsonFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	CrimsonFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	CrimsonFungus,
	CrimsonHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	CrimsonHyphae {
		axis: Axis3D,
	},
	CrimsonNylium,
	CrimsonPlanks,
	CrimsonPressurePlate {
		powered: bool,
	},
	CrimsonRoots,
	CrimsonSign {
		rotation: u8,
		waterlogged: bool,
	},
	CrimsonSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CrimsonStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CrimsonStem {
		axis: Axis3D,
	},
	CrimsonTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	CrimsonWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	CrimsonWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	CryingObsidian,
	CutCopper,
	CutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CutRedSandstone,
	CutRedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CutSandstone,
	CutSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CyanBanner {
		rotation: u8,
	},
	CyanBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	CyanCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	CyanCandleCake {
		lit: bool,
	},
	CyanCarpet,
	CyanConcrete,
	CyanConcretePowder,
	CyanGlazedTerracotta {
		facing: Direction,
	},
	CyanShulkerBox {
		facing: Facing,
	},
	CyanStainedGlass,
	CyanStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	CyanTerracotta,
	CyanWallBanner {
		facing: Direction,
	},
	CyanWool,
	DamagedAnvil {
		facing: Direction,
	},
	Dandelion,
	DarkOakButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	DarkOakDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	DarkOakFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	DarkOakFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	DarkOakHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	DarkOakLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	DarkOakLog {
		axis: Axis3D,
	},
	DarkOakPlanks,
	DarkOakPressurePlate {
		powered: bool,
	},
	DarkOakSapling {
		stage: u8,
	},
	DarkOakSign {
		rotation: u8,
		waterlogged: bool,
	},
	DarkOakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DarkOakStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DarkOakTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	DarkOakWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	DarkOakWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	DarkOakWood {
		axis: Axis3D,
	},
	DarkPrismarine,
	DarkPrismarineSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DarkPrismarineStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DaylightDetector {
		inverted: bool,
		power: u8,
	},
	DeadBrainCoral {
		waterlogged: bool,
	},
	DeadBrainCoralBlock,
	DeadBrainCoralFan {
		waterlogged: bool,
	},
	DeadBrainCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadBubbleCoral {
		waterlogged: bool,
	},
	DeadBubbleCoralBlock,
	DeadBubbleCoralFan {
		waterlogged: bool,
	},
	DeadBubbleCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadBush,
	DeadFireCoral {
		waterlogged: bool,
	},
	DeadFireCoralBlock,
	DeadFireCoralFan {
		waterlogged: bool,
	},
	DeadFireCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadHornCoral {
		waterlogged: bool,
	},
	DeadHornCoralBlock,
	DeadHornCoralFan {
		waterlogged: bool,
	},
	DeadHornCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadTubeCoral {
		waterlogged: bool,
	},
	DeadTubeCoralBlock,
	DeadTubeCoralFan {
		waterlogged: bool,
	},
	DeadTubeCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DecoratedPot {
		cracked: bool,
		facing: Direction,
		waterlogged: bool,
	},
	Deepslate {
		axis: Axis3D,
	},
	DeepslateBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DeepslateBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DeepslateBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	DeepslateBricks,
	DeepslateCoalOre,
	DeepslateCopperOre,
	DeepslateDiamondOre,
	DeepslateEmeraldOre,
	DeepslateGoldOre,
	DeepslateIronOre,
	DeepslateLapisOre,
	DeepslateRedstoneOre {
		lit: bool,
	},
	DeepslateTileSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DeepslateTileStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DeepslateTileWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	DeepslateTiles,
	DetectorRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	DiamondBlock,
	DiamondOre,
	Diorite,
	DioriteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DioriteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DioriteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Dirt,
	DirtPath,
	Dispenser {
		facing: Facing,
		triggered: bool,
	},
	DragonEgg,
	DragonHead {
		powered: bool,
		rotation: u8,
	},
	DragonWallHead {
		facing: Direction,
		powered: bool,
	},
	DriedKelpBlock,
	DripstoneBlock,
	Dropper {
		facing: Facing,
		triggered: bool,
	},
	EmeraldBlock,
	EmeraldOre,
	EnchantingTable,
	EndGateway,
	EndPortal,
	EndPortalFrame {
		eye: bool,
		facing: Direction,
	},
	EndRod {
		facing: Facing,
	},
	EndStone,
	EndStoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	EndStoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	EndStoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	EndStoneBricks,
	EnderChest {
		facing: Direction,
		waterlogged: bool,
	},
	ExposedChiseledCopper,
	ExposedCopper,
	ExposedCopperBulb {
		lit: bool,
		powered: bool,
	},
	ExposedCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	ExposedCopperGrate {
		waterlogged: bool,
	},
	ExposedCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	ExposedCutCopper,
	ExposedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	ExposedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	Farmland {
		moisture: u8,
	},
	Fern,
	Fire {
		age: u8,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	FireCoral {
		waterlogged: bool,
	},
	FireCoralBlock,
	FireCoralFan {
		waterlogged: bool,
	},
	FireCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	FletchingTable,
	FlowerPot,
	FloweringAzalea,
	FloweringAzaleaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	Frogspawn,
	FrostedIce {
		age: u8,
	},
	Furnace {
		facing: Direction,
		lit: bool,
	},
	GildedBlackstone,
	Glass,
	GlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	GlowLichen {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		waterlogged: bool,
		west: bool,
	},
	Glowstone,
	GoldBlock,
	GoldOre,
	Granite,
	GraniteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	GraniteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	GraniteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	GrassBlock {
		snowy: bool,
	},
	Gravel,
	GrayBanner {
		rotation: u8,
	},
	GrayBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	GrayCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	GrayCandleCake {
		lit: bool,
	},
	GrayCarpet,
	GrayConcrete,
	GrayConcretePowder,
	GrayGlazedTerracotta {
		facing: Direction,
	},
	GrayShulkerBox {
		facing: Facing,
	},
	GrayStainedGlass,
	GrayStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	GrayTerracotta,
	GrayWallBanner {
		facing: Direction,
	},
	GrayWool,
	GreenBanner {
		rotation: u8,
	},
	GreenBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	GreenCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	GreenCandleCake {
		lit: bool,
	},
	GreenCarpet,
	GreenConcrete,
	GreenConcretePowder,
	GreenGlazedTerracotta {
		facing: Direction,
	},
	GreenShulkerBox {
		facing: Facing,
	},
	GreenStainedGlass,
	GreenStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	GreenTerracotta,
	GreenWallBanner {
		facing: Direction,
	},
	GreenWool,
	Grindstone {
		face: Face,
		facing: Direction,
	},
	HangingRoots {
		waterlogged: bool,
	},
	HayBlock {
		axis: Axis3D,
	},
	HeavyWeightedPressurePlate {
		power: u8,
	},
	HoneyBlock,
	HoneycombBlock,
	Hopper {
		enabled: bool,
		facing: DirectionOrDown,
	},
	HornCoral {
		waterlogged: bool,
	},
	HornCoralBlock,
	HornCoralFan {
		waterlogged: bool,
	},
	HornCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	Ice,
	InfestedChiseledStoneBricks,
	InfestedCobblestone,
	InfestedCrackedStoneBricks,
	InfestedDeepslate {
		axis: Axis3D,
	},
	InfestedMossyStoneBricks,
	InfestedStone,
	InfestedStoneBricks,
	IronBars {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	IronBlock,
	IronDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	IronOre,
	IronTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	JackOLantern {
		facing: Direction,
	},
	Jigsaw {
		orientation: Orientation,
	},
	Jukebox {
		has_record: bool,
	},
	JungleButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	JungleDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	JungleFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	JungleFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	JungleHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	JungleLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	JungleLog {
		axis: Axis3D,
	},
	JunglePlanks,
	JunglePressurePlate {
		powered: bool,
	},
	JungleSapling {
		stage: u8,
	},
	JungleSign {
		rotation: u8,
		waterlogged: bool,
	},
	JungleSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	JungleStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	JungleTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	JungleWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	JungleWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	JungleWood {
		axis: Axis3D,
	},
	Kelp {
		age: u8,
	},
	KelpPlant,
	Ladder {
		facing: Direction,
		waterlogged: bool,
	},
	Lantern {
		hanging: bool,
		waterlogged: bool,
	},
	LapisBlock,
	LapisOre,
	LargeAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	LargeFern {
		half: UpperOrLower,
	},
	Lava {
		level: u8,
	},
	LavaCauldron,
	Lectern {
		facing: Direction,
		has_book: bool,
		powered: bool,
	},
	Lever {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	Light {
		level: u8,
		waterlogged: bool,
	},
	LightBlueBanner {
		rotation: u8,
	},
	LightBlueBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LightBlueCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LightBlueCandleCake {
		lit: bool,
	},
	LightBlueCarpet,
	LightBlueConcrete,
	LightBlueConcretePowder,
	LightBlueGlazedTerracotta {
		facing: Direction,
	},
	LightBlueShulkerBox {
		facing: Facing,
	},
	LightBlueStainedGlass,
	LightBlueStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LightBlueTerracotta,
	LightBlueWallBanner {
		facing: Direction,
	},
	LightBlueWool,
	LightGrayBanner {
		rotation: u8,
	},
	LightGrayBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LightGrayCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LightGrayCandleCake {
		lit: bool,
	},
	LightGrayCarpet,
	LightGrayConcrete,
	LightGrayConcretePowder,
	LightGrayGlazedTerracotta {
		facing: Direction,
	},
	LightGrayShulkerBox {
		facing: Facing,
	},
	LightGrayStainedGlass,
	LightGrayStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LightGrayTerracotta,
	LightGrayWallBanner {
		facing: Direction,
	},
	LightGrayWool,
	LightWeightedPressurePlate {
		power: u8,
	},
	LightningRod {
		facing: Facing,
		powered: bool,
		waterlogged: bool,
	},
	Lilac {
		half: UpperOrLower,
	},
	LilyOfTheValley,
	LilyPad,
	LimeBanner {
		rotation: u8,
	},
	LimeBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LimeCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LimeCandleCake {
		lit: bool,
	},
	LimeCarpet,
	LimeConcrete,
	LimeConcretePowder,
	LimeGlazedTerracotta {
		facing: Direction,
	},
	LimeShulkerBox {
		facing: Facing,
	},
	LimeStainedGlass,
	LimeStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LimeTerracotta,
	LimeWallBanner {
		facing: Direction,
	},
	LimeWool,
	Lodestone,
	Loom {
		facing: Direction,
	},
	MagentaBanner {
		rotation: u8,
	},
	MagentaBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	MagentaCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	MagentaCandleCake {
		lit: bool,
	},
	MagentaCarpet,
	MagentaConcrete,
	MagentaConcretePowder,
	MagentaGlazedTerracotta {
		facing: Direction,
	},
	MagentaShulkerBox {
		facing: Facing,
	},
	MagentaStainedGlass,
	MagentaStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	MagentaTerracotta,
	MagentaWallBanner {
		facing: Direction,
	},
	MagentaWool,
	MagmaBlock,
	MangroveButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	MangroveDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	MangroveFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	MangroveFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	MangroveHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	MangroveLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	MangroveLog {
		axis: Axis3D,
	},
	MangrovePlanks,
	MangrovePressurePlate {
		powered: bool,
	},
	MangrovePropagule {
		age: u8,
		hanging: bool,
		stage: u8,
		waterlogged: bool,
	},
	MangroveRoots {
		waterlogged: bool,
	},
	MangroveSign {
		rotation: u8,
		waterlogged: bool,
	},
	MangroveSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MangroveStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MangroveTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	MangroveWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	MangroveWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	MangroveWood {
		axis: Axis3D,
	},
	MediumAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	Melon,
	MelonStem {
		age: u8,
	},
	MossBlock,
	MossCarpet,
	MossyCobblestone,
	MossyCobblestoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MossyCobblestoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MossyCobblestoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MossyStoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MossyStoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MossyStoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MossyStoneBricks,
	MovingPiston {
		block_type: PistonType,
		facing: Facing,
	},
	Mud,
	MudBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MudBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MudBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MudBricks,
	MuddyMangroveRoots {
		axis: Axis3D,
	},
	MushroomStem {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	Mycelium {
		snowy: bool,
	},
	NetherBrickFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	NetherBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	NetherBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	NetherBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	NetherBricks,
	NetherGoldOre,
	NetherPortal {
		axis: Axis2D,
	},
	NetherQuartzOre,
	NetherSprouts,
	NetherWart {
		age: u8,
	},
	NetherWartBlock,
	NetheriteBlock,
	Netherrack,
	NoteBlock {
		instrument: Instrument,
		note: u8,
		powered: bool,
	},
	OakButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	OakDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	OakFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	OakFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	OakHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	OakLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	OakLog {
		axis: Axis3D,
	},
	OakPlanks,
	OakPressurePlate {
		powered: bool,
	},
	OakSapling {
		stage: u8,
	},
	OakSign {
		rotation: u8,
		waterlogged: bool,
	},
	OakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	OakStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	OakTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	OakWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	OakWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	OakWood {
		axis: Axis3D,
	},
	Observer {
		facing: Facing,
		powered: bool,
	},
	Obsidian,
	OchreFroglight {
		axis: Axis3D,
	},
	OrangeBanner {
		rotation: u8,
	},
	OrangeBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	OrangeCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	OrangeCandleCake {
		lit: bool,
	},
	OrangeCarpet,
	OrangeConcrete,
	OrangeConcretePowder,
	OrangeGlazedTerracotta {
		facing: Direction,
	},
	OrangeShulkerBox {
		facing: Facing,
	},
	OrangeStainedGlass,
	OrangeStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	OrangeTerracotta,
	OrangeTulip,
	OrangeWallBanner {
		facing: Direction,
	},
	OrangeWool,
	OxeyeDaisy,
	OxidizedChiseledCopper,
	OxidizedCopper,
	OxidizedCopperBulb {
		lit: bool,
		powered: bool,
	},
	OxidizedCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	OxidizedCopperGrate {
		waterlogged: bool,
	},
	OxidizedCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	OxidizedCutCopper,
	OxidizedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	OxidizedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PackedIce,
	PackedMud,
	PearlescentFroglight {
		axis: Axis3D,
	},
	Peony {
		half: UpperOrLower,
	},
	PetrifiedOakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PiglinHead {
		powered: bool,
		rotation: u8,
	},
	PiglinWallHead {
		facing: Direction,
		powered: bool,
	},
	PinkBanner {
		rotation: u8,
	},
	PinkBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	PinkCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	PinkCandleCake {
		lit: bool,
	},
	PinkCarpet,
	PinkConcrete,
	PinkConcretePowder,
	PinkGlazedTerracotta {
		facing: Direction,
	},
	PinkPetals {
		facing: Direction,
		flower_amount: u8,
	},
	PinkShulkerBox {
		facing: Facing,
	},
	PinkStainedGlass,
	PinkStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	PinkTerracotta,
	PinkTulip,
	PinkWallBanner {
		facing: Direction,
	},
	PinkWool,
	Piston {
		extended: bool,
		facing: Facing,
	},
	PistonHead {
		block_type: PistonType,
		facing: Facing,
		short: bool,
	},
	PitcherCrop {
		age: u8,
		half: UpperOrLower,
	},
	PitcherPlant {
		half: UpperOrLower,
	},
	PlayerHead {
		powered: bool,
		rotation: u8,
	},
	PlayerWallHead {
		facing: Direction,
		powered: bool,
	},
	Podzol {
		snowy: bool,
	},
	PointedDripstone {
		thickness: Thickness,
		vertical_direction: VerticalDirection,
		waterlogged: bool,
	},
	PolishedAndesite,
	PolishedAndesiteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedAndesiteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedBasalt {
		axis: Axis3D,
	},
	PolishedBlackstone,
	PolishedBlackstoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedBlackstoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedBlackstoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	PolishedBlackstoneBricks,
	PolishedBlackstoneButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	PolishedBlackstonePressurePlate {
		powered: bool,
	},
	PolishedBlackstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedBlackstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedBlackstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	PolishedDeepslate,
	PolishedDeepslateSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedDeepslateStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedDeepslateWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	PolishedDiorite,
	PolishedDioriteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedDioriteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedGranite,
	PolishedGraniteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedGraniteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedTuff,
	PolishedTuffSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedTuffStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedTuffWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Poppy,
	Potatoes {
		age: u8,
	},
	PottedAcaciaSapling,
	PottedAllium,
	PottedAzaleaBush,
	PottedAzureBluet,
	PottedBamboo,
	PottedBirchSapling,
	PottedBlueOrchid,
	PottedBrownMushroom,
	PottedCactus,
	PottedCherrySapling,
	PottedCornflower,
	PottedCrimsonFungus,
	PottedCrimsonRoots,
	PottedDandelion,
	PottedDarkOakSapling,
	PottedDeadBush,
	PottedFern,
	PottedFloweringAzaleaBush,
	PottedJungleSapling,
	PottedLilyOfTheValley,
	PottedMangrovePropagule,
	PottedOakSapling,
	PottedOrangeTulip,
	PottedOxeyeDaisy,
	PottedPinkTulip,
	PottedPoppy,
	PottedRedMushroom,
	PottedRedTulip,
	PottedSpruceSapling,
	PottedTorchflower,
	PottedWarpedFungus,
	PottedWarpedRoots,
	PottedWhiteTulip,
	PottedWitherRose,
	PowderSnow,
	PowderSnowCauldron {
		level: u8,
	},
	PoweredRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	Prismarine,
	PrismarineBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PrismarineBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PrismarineBricks,
	PrismarineSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PrismarineStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PrismarineWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Pumpkin,
	PumpkinStem {
		age: u8,
	},
	PurpleBanner {
		rotation: u8,
	},
	PurpleBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	PurpleCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	PurpleCandleCake {
		lit: bool,
	},
	PurpleCarpet,
	PurpleConcrete,
	PurpleConcretePowder,
	PurpleGlazedTerracotta {
		facing: Direction,
	},
	PurpleShulkerBox {
		facing: Facing,
	},
	PurpleStainedGlass,
	PurpleStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	PurpleTerracotta,
	PurpleWallBanner {
		facing: Direction,
	},
	PurpleWool,
	PurpurBlock,
	PurpurPillar {
		axis: Axis3D,
	},
	PurpurSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PurpurStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	QuartzBlock,
	QuartzBricks,
	QuartzPillar {
		axis: Axis3D,
	},
	QuartzSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	QuartzStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	Rail {
		shape: RailShape,
		waterlogged: bool,
	},
	RawCopperBlock,
	RawGoldBlock,
	RawIronBlock,
	RedBanner {
		rotation: u8,
	},
	RedBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	RedCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	RedCandleCake {
		lit: bool,
	},
	RedCarpet,
	RedConcrete,
	RedConcretePowder,
	RedGlazedTerracotta {
		facing: Direction,
	},
	RedMushroom,
	RedMushroomBlock {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	RedNetherBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	RedNetherBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	RedNetherBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	RedNetherBricks,
	RedSand,
	RedSandstone,
	RedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	RedSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	RedSandstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	RedShulkerBox {
		facing: Facing,
	},
	RedStainedGlass,
	RedStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	RedTerracotta,
	RedTulip,
	RedWallBanner {
		facing: Direction,
	},
	RedWool,
	RedstoneBlock,
	RedstoneLamp {
		lit: bool,
	},
	RedstoneOre {
		lit: bool,
	},
	RedstoneTorch {
		lit: bool,
	},
	RedstoneWallTorch {
		facing: Direction,
		lit: bool,
	},
	RedstoneWire {
		east: WireConnection,
		north: WireConnection,
		power: u8,
		south: WireConnection,
		west: WireConnection,
	},
	ReinforcedDeepslate,
	Repeater {
		delay: u8,
		facing: Direction,
		locked: bool,
		powered: bool,
	},
	RepeatingCommandBlock {
		conditional: bool,
		facing: Facing,
	},
	RespawnAnchor {
		charges: u8,
	},
	RootedDirt,
	RoseBush {
		half: UpperOrLower,
	},
	Sand,
	Sandstone,
	SandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SandstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Scaffolding {
		bottom: bool,
		distance: u8,
		waterlogged: bool,
	},
	Sculk,
	SculkCatalyst {
		bloom: bool,
	},
	SculkSensor {
		power: u8,
		sculk_sensor_phase: SculkSensorPhase,
		waterlogged: bool,
	},
	SculkShrieker {
		can_summon: bool,
		shrieking: bool,
		waterlogged: bool,
	},
	SculkVein {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		waterlogged: bool,
		west: bool,
	},
	SeaLantern,
	SeaPickle {
		pickles: u8,
		waterlogged: bool,
	},
	Seagrass,
	ShortGrass,
	Shroomlight,
	ShulkerBox {
		facing: Facing,
	},
	SkeletonSkull {
		powered: bool,
		rotation: u8,
	},
	SkeletonWallSkull {
		facing: Direction,
		powered: bool,
	},
	SlimeBlock,
	SmallAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	SmallDripleaf {
		facing: Direction,
		half: UpperOrLower,
		waterlogged: bool,
	},
	SmithingTable,
	Smoker {
		facing: Direction,
		lit: bool,
	},
	SmoothBasalt,
	SmoothQuartz,
	SmoothQuartzSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothQuartzStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothRedSandstone,
	SmoothRedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothRedSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothSandstone,
	SmoothSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothStone,
	SmoothStoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SnifferEgg {
		hatch: u8,
	},
	Snow {
		layers: u8,
	},
	SnowBlock,
	SoulCampfire {
		facing: Direction,
		lit: bool,
		signal_fire: bool,
		waterlogged: bool,
	},
	SoulFire,
	SoulLantern {
		hanging: bool,
		waterlogged: bool,
	},
	SoulSand,
	SoulSoil,
	SoulTorch,
	SoulWallTorch {
		facing: Direction,
	},
	Spawner,
	Sponge,
	SporeBlossom,
	SpruceButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	SpruceDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	SpruceFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	SpruceFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	SpruceHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	SpruceLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	SpruceLog {
		axis: Axis3D,
	},
	SprucePlanks,
	SprucePressurePlate {
		powered: bool,
	},
	SpruceSapling {
		stage: u8,
	},
	SpruceSign {
		rotation: u8,
		waterlogged: bool,
	},
	SpruceSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SpruceStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SpruceTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	SpruceWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	SpruceWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	SpruceWood {
		axis: Axis3D,
	},
	StickyPiston {
		extended: bool,
		facing: Facing,
	},
	Stone,
	StoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	StoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	StoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	StoneBricks,
	StoneButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	StonePressurePlate {
		powered: bool,
	},
	StoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	StoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	Stonecutter {
		facing: Direction,
	},
	StrippedAcaciaLog {
		axis: Axis3D,
	},
	StrippedAcaciaWood {
		axis: Axis3D,
	},
	StrippedBambooBlock {
		axis: Axis3D,
	},
	StrippedBirchLog {
		axis: Axis3D,
	},
	StrippedBirchWood {
		axis: Axis3D,
	},
	StrippedCherryLog {
		axis: Axis3D,
	},
	StrippedCherryWood {
		axis: Axis3D,
	},
	StrippedCrimsonHyphae {
		axis: Axis3D,
	},
	StrippedCrimsonStem {
		axis: Axis3D,
	},
	StrippedDarkOakLog {
		axis: Axis3D,
	},
	StrippedDarkOakWood {
		axis: Axis3D,
	},
	StrippedJungleLog {
		axis: Axis3D,
	},
	StrippedJungleWood {
		axis: Axis3D,
	},
	StrippedMangroveLog {
		axis: Axis3D,
	},
	StrippedMangroveWood {
		axis: Axis3D,
	},
	StrippedOakLog {
		axis: Axis3D,
	},
	StrippedOakWood {
		axis: Axis3D,
	},
	StrippedSpruceLog {
		axis: Axis3D,
	},
	StrippedSpruceWood {
		axis: Axis3D,
	},
	StrippedWarpedHyphae {
		axis: Axis3D,
	},
	StrippedWarpedStem {
		axis: Axis3D,
	},
	StructureBlock {
		mode: StructureBlockMode,
	},
	StructureVoid,
	SugarCane {
		age: u8,
	},
	Sunflower {
		half: UpperOrLower,
	},
	SuspiciousGravel {
		dusted: u8,
	},
	SuspiciousSand {
		dusted: u8,
	},
	SweetBerryBush {
		age: u8,
	},
	TallGrass {
		half: UpperOrLower,
	},
	TallSeagrass {
		half: UpperOrLower,
	},
	Target {
		power: u8,
	},
	Terracotta,
	TintedGlass,
	Tnt {
		unstable: bool,
	},
	Torch,
	Torchflower,
	TorchflowerCrop {
		age: u8,
	},
	TrappedChest {
		block_type: ChestType,
		facing: Direction,
		waterlogged: bool,
	},
	TrialSpawner {
		trial_spawner_state: TrialSpawnerState,
	},
	Tripwire {
		attached: bool,
		disarmed: bool,
		east: bool,
		north: bool,
		powered: bool,
		south: bool,
		west: bool,
	},
	TripwireHook {
		attached: bool,
		facing: Direction,
		powered: bool,
	},
	TubeCoral {
		waterlogged: bool,
	},
	TubeCoralBlock,
	TubeCoralFan {
		waterlogged: bool,
	},
	TubeCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	Tuff,
	TuffBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	TuffBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	TuffBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	TuffBricks,
	TuffSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	TuffStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	TuffWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	TurtleEgg {
		eggs: u8,
		hatch: u8,
	},
	TwistingVines {
		age: u8,
	},
	TwistingVinesPlant,
	VerdantFroglight {
		axis: Axis3D,
	},
	Vine {
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	VoidAir,
	WallTorch {
		facing: Direction,
	},
	WarpedButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	WarpedDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WarpedFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	WarpedFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	WarpedFungus,
	WarpedHangingSign {
		attached: bool,
		rotation: u8,
		waterlogged: bool,
	},
	WarpedHyphae {
		axis: Axis3D,
	},
	WarpedNylium,
	WarpedPlanks,
	WarpedPressurePlate {
		powered: bool,
	},
	WarpedRoots,
	WarpedSign {
		rotation: u8,
		waterlogged: bool,
	},
	WarpedSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WarpedStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WarpedStem {
		axis: Axis3D,
	},
	WarpedTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WarpedWallHangingSign {
		facing: Direction,
		waterlogged: bool,
	},
	WarpedWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	WarpedWartBlock,
	Water {
		level: u8,
	},
	WaterCauldron {
		level: u8,
	},
	WaxedChiseledCopper,
	WaxedCopperBlock,
	WaxedCopperBulb {
		lit: bool,
		powered: bool,
	},
	WaxedCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WaxedCopperGrate {
		waterlogged: bool,
	},
	WaxedCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WaxedCutCopper,
	WaxedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedExposedChiseledCopper,
	WaxedExposedCopper,
	WaxedExposedCopperBulb {
		lit: bool,
		powered: bool,
	},
	WaxedExposedCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WaxedExposedCopperGrate {
		waterlogged: bool,
	},
	WaxedExposedCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WaxedExposedCutCopper,
	WaxedExposedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedExposedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedOxidizedChiseledCopper,
	WaxedOxidizedCopper,
	WaxedOxidizedCopperBulb {
		lit: bool,
		powered: bool,
	},
	WaxedOxidizedCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WaxedOxidizedCopperGrate {
		waterlogged: bool,
	},
	WaxedOxidizedCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WaxedOxidizedCutCopper,
	WaxedOxidizedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedOxidizedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedWeatheredChiseledCopper,
	WaxedWeatheredCopper,
	WaxedWeatheredCopperBulb {
		lit: bool,
		powered: bool,
	},
	WaxedWeatheredCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WaxedWeatheredCopperGrate {
		waterlogged: bool,
	},
	WaxedWeatheredCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WaxedWeatheredCutCopper,
	WaxedWeatheredCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedWeatheredCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WeatheredChiseledCopper,
	WeatheredCopper,
	WeatheredCopperBulb {
		lit: bool,
		powered: bool,
	},
	WeatheredCopperDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WeatheredCopperGrate {
		waterlogged: bool,
	},
	WeatheredCopperTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WeatheredCutCopper,
	WeatheredCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WeatheredCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WeepingVines {
		age: u8,
	},
	WeepingVinesPlant,
	WetSponge,
	Wheat {
		age: u8,
	},
	WhiteBanner {
		rotation: u8,
	},
	WhiteBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	WhiteCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	WhiteCandleCake {
		lit: bool,
	},
	WhiteCarpet,
	WhiteConcrete,
	WhiteConcretePowder,
	WhiteGlazedTerracotta {
		facing: Direction,
	},
	WhiteShulkerBox {
		facing: Facing,
	},
	WhiteStainedGlass,
	WhiteStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	WhiteTerracotta,
	WhiteTulip,
	WhiteWallBanner {
		facing: Direction,
	},
	WhiteWool,
	WitherRose,
	WitherSkeletonSkull {
		powered: bool,
		rotation: u8,
	},
	WitherSkeletonWallSkull {
		facing: Direction,
		powered: bool,
	},
	YellowBanner {
		rotation: u8,
	},
	YellowBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	YellowCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	YellowCandleCake {
		lit: bool,
	},
	YellowCarpet,
	YellowConcrete,
	YellowConcretePowder,
	YellowGlazedTerracotta {
		facing: Direction,
	},
	YellowShulkerBox {
		facing: Facing,
	},
	YellowStainedGlass,
	YellowStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	YellowTerracotta,
	YellowWallBanner {
		facing: Direction,
	},
	YellowWool,
	ZombieHead {
		powered: bool,
		rotation: u8,
	},
	ZombieWallHead {
		facing: Direction,
		powered: bool,
	},
}

