// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs
// Data is provided courtesy of `https://github.com/Minestom/MinestomDataGenerator`

use crate::block_parameter::*;

include!(concat!(env!("OUT_DIR"), "/block_to_u16.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_block.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_item.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_block_attributes.rs"));

pub fn state_to_item(id: u16) -> Result<crate::item::Item, NoSuchBlockError> {
	if id >= ITEM_LUT.len() as _ { return Err(NoSuchBlockError(id)); }
	Ok(ITEM_LUT[id as usize])
}
#[derive(Debug)]
pub struct BlockAttributes {
	pub hardness: f32,
	pub replaceable: bool,
	pub air: bool,
	pub is_north_face_sturdy: bool,
	pub is_east_face_sturdy: bool,
	pub is_south_face_sturdy: bool,
	pub is_west_face_sturdy: bool,
	pub is_up_face_sturdy: bool,
}

#[derive(Debug, thiserror::Error)]
#[error("No block exists for id: {0}")]
pub struct NoSuchBlockError(u16);

#[derive(Debug, Clone)]
pub enum Block {
	Air,
	Stone,
	Granite,
	PolishedGranite,
	Diorite,
	PolishedDiorite,
	Andesite,
	PolishedAndesite,
	GrassBlock {
		snowy: bool,
	},
	Dirt,
	CoarseDirt,
	Podzol {
		snowy: bool,
	},
	Cobblestone,
	OakPlanks,
	SprucePlanks,
	BirchPlanks,
	JunglePlanks,
	AcaciaPlanks,
	DarkOakPlanks,
	MangrovePlanks,
	OakSapling {
		stage: u8,
	},
	SpruceSapling {
		stage: u8,
	},
	BirchSapling {
		stage: u8,
	},
	JungleSapling {
		stage: u8,
	},
	AcaciaSapling {
		stage: u8,
	},
	DarkOakSapling {
		stage: u8,
	},
	MangrovePropagule {
		age: u8,
		hanging: bool,
		stage: u8,
		waterlogged: bool,
	},
	Bedrock,
	Water {
		level: u8,
	},
	Lava {
		level: u8,
	},
	Sand,
	RedSand,
	Gravel,
	GoldOre,
	DeepslateGoldOre,
	IronOre,
	DeepslateIronOre,
	CoalOre,
	DeepslateCoalOre,
	NetherGoldOre,
	OakLog {
		axis: Axis3D,
	},
	SpruceLog {
		axis: Axis3D,
	},
	BirchLog {
		axis: Axis3D,
	},
	JungleLog {
		axis: Axis3D,
	},
	AcaciaLog {
		axis: Axis3D,
	},
	DarkOakLog {
		axis: Axis3D,
	},
	MangroveLog {
		axis: Axis3D,
	},
	MangroveRoots {
		waterlogged: bool,
	},
	MuddyMangroveRoots {
		axis: Axis3D,
	},
	StrippedSpruceLog {
		axis: Axis3D,
	},
	StrippedBirchLog {
		axis: Axis3D,
	},
	StrippedJungleLog {
		axis: Axis3D,
	},
	StrippedAcaciaLog {
		axis: Axis3D,
	},
	StrippedDarkOakLog {
		axis: Axis3D,
	},
	StrippedOakLog {
		axis: Axis3D,
	},
	StrippedMangroveLog {
		axis: Axis3D,
	},
	OakWood {
		axis: Axis3D,
	},
	SpruceWood {
		axis: Axis3D,
	},
	BirchWood {
		axis: Axis3D,
	},
	JungleWood {
		axis: Axis3D,
	},
	AcaciaWood {
		axis: Axis3D,
	},
	DarkOakWood {
		axis: Axis3D,
	},
	MangroveWood {
		axis: Axis3D,
	},
	StrippedOakWood {
		axis: Axis3D,
	},
	StrippedSpruceWood {
		axis: Axis3D,
	},
	StrippedBirchWood {
		axis: Axis3D,
	},
	StrippedJungleWood {
		axis: Axis3D,
	},
	StrippedAcaciaWood {
		axis: Axis3D,
	},
	StrippedDarkOakWood {
		axis: Axis3D,
	},
	StrippedMangroveWood {
		axis: Axis3D,
	},
	OakLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	SpruceLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	BirchLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	JungleLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	AcaciaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	DarkOakLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	MangroveLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	AzaleaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	FloweringAzaleaLeaves {
		distance: u8,
		persistent: bool,
		waterlogged: bool,
	},
	Sponge,
	WetSponge,
	Glass,
	LapisOre,
	DeepslateLapisOre,
	LapisBlock,
	Dispenser {
		facing: Facing,
		triggered: bool,
	},
	Sandstone,
	ChiseledSandstone,
	CutSandstone,
	NoteBlock {
		instrument: Instrument,
		note: u8,
		powered: bool,
	},
	WhiteBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	OrangeBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	MagentaBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LightBlueBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	YellowBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LimeBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	PinkBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	GrayBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	LightGrayBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	CyanBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	PurpleBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BlueBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BrownBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	GreenBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	RedBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	BlackBed {
		facing: Direction,
		occupied: bool,
		part: Part,
	},
	PoweredRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	DetectorRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	StickyPiston {
		extended: bool,
		facing: Facing,
	},
	Cobweb,
	Grass,
	Fern,
	DeadBush,
	Seagrass,
	TallSeagrass {
		half: UpperOrLower,
	},
	Piston {
		extended: bool,
		facing: Facing,
	},
	PistonHead {
		facing: Facing,
		short: bool,
		block_type: PistonType,
	},
	WhiteWool,
	OrangeWool,
	MagentaWool,
	LightBlueWool,
	YellowWool,
	LimeWool,
	PinkWool,
	GrayWool,
	LightGrayWool,
	CyanWool,
	PurpleWool,
	BlueWool,
	BrownWool,
	GreenWool,
	RedWool,
	BlackWool,
	MovingPiston {
		facing: Facing,
		block_type: PistonType,
	},
	Dandelion,
	Poppy,
	BlueOrchid,
	Allium,
	AzureBluet,
	RedTulip,
	OrangeTulip,
	WhiteTulip,
	PinkTulip,
	OxeyeDaisy,
	Cornflower,
	WitherRose,
	LilyOfTheValley,
	BrownMushroom,
	RedMushroom,
	GoldBlock,
	IronBlock,
	Bricks,
	Tnt {
		unstable: bool,
	},
	Bookshelf,
	MossyCobblestone,
	Obsidian,
	Torch,
	WallTorch {
		facing: Direction,
	},
	Fire {
		age: u8,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	SoulFire,
	Spawner,
	OakStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	Chest {
		facing: Direction,
		block_type: ChestType,
		waterlogged: bool,
	},
	RedstoneWire {
		east: WireConnection,
		north: WireConnection,
		power: u8,
		south: WireConnection,
		west: WireConnection,
	},
	DiamondOre,
	DeepslateDiamondOre,
	DiamondBlock,
	CraftingTable,
	Wheat {
		age: u8,
	},
	Farmland {
		moisture: u8,
	},
	Furnace {
		facing: Direction,
		lit: bool,
	},
	OakSign {
		rotation: u8,
		waterlogged: bool,
	},
	SpruceSign {
		rotation: u8,
		waterlogged: bool,
	},
	BirchSign {
		rotation: u8,
		waterlogged: bool,
	},
	AcaciaSign {
		rotation: u8,
		waterlogged: bool,
	},
	JungleSign {
		rotation: u8,
		waterlogged: bool,
	},
	DarkOakSign {
		rotation: u8,
		waterlogged: bool,
	},
	MangroveSign {
		rotation: u8,
		waterlogged: bool,
	},
	OakDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	Ladder {
		facing: Direction,
		waterlogged: bool,
	},
	Rail {
		shape: RailShape,
		waterlogged: bool,
	},
	CobblestoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	OakWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	SpruceWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	BirchWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	AcaciaWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	JungleWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	DarkOakWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	MangroveWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	Lever {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	StonePressurePlate {
		powered: bool,
	},
	IronDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	OakPressurePlate {
		powered: bool,
	},
	SprucePressurePlate {
		powered: bool,
	},
	BirchPressurePlate {
		powered: bool,
	},
	JunglePressurePlate {
		powered: bool,
	},
	AcaciaPressurePlate {
		powered: bool,
	},
	DarkOakPressurePlate {
		powered: bool,
	},
	MangrovePressurePlate {
		powered: bool,
	},
	RedstoneOre {
		lit: bool,
	},
	DeepslateRedstoneOre {
		lit: bool,
	},
	RedstoneTorch {
		lit: bool,
	},
	RedstoneWallTorch {
		facing: Direction,
		lit: bool,
	},
	StoneButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	Snow {
		layers: u8,
	},
	Ice,
	SnowBlock,
	Cactus {
		age: u8,
	},
	Clay,
	SugarCane {
		age: u8,
	},
	Jukebox {
		has_record: bool,
	},
	OakFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	Pumpkin,
	Netherrack,
	SoulSand,
	SoulSoil,
	Basalt {
		axis: Axis3D,
	},
	PolishedBasalt {
		axis: Axis3D,
	},
	SoulTorch,
	SoulWallTorch {
		facing: Direction,
	},
	Glowstone,
	NetherPortal {
		axis: Axis2D,
	},
	CarvedPumpkin {
		facing: Direction,
	},
	JackOLantern {
		facing: Direction,
	},
	Cake {
		bites: u8,
	},
	Repeater {
		delay: u8,
		facing: Direction,
		locked: bool,
		powered: bool,
	},
	WhiteStainedGlass,
	OrangeStainedGlass,
	MagentaStainedGlass,
	LightBlueStainedGlass,
	YellowStainedGlass,
	LimeStainedGlass,
	PinkStainedGlass,
	GrayStainedGlass,
	LightGrayStainedGlass,
	CyanStainedGlass,
	PurpleStainedGlass,
	BlueStainedGlass,
	BrownStainedGlass,
	GreenStainedGlass,
	RedStainedGlass,
	BlackStainedGlass,
	OakTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	SpruceTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	BirchTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	JungleTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	AcaciaTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	DarkOakTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	MangroveTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	StoneBricks,
	MossyStoneBricks,
	CrackedStoneBricks,
	ChiseledStoneBricks,
	PackedMud,
	MudBricks,
	InfestedStone,
	InfestedCobblestone,
	InfestedStoneBricks,
	InfestedMossyStoneBricks,
	InfestedCrackedStoneBricks,
	InfestedChiseledStoneBricks,
	BrownMushroomBlock {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	RedMushroomBlock {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	MushroomStem {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	IronBars {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	Chain {
		axis: Axis3D,
		waterlogged: bool,
	},
	GlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	Melon,
	AttachedPumpkinStem {
		facing: Direction,
	},
	AttachedMelonStem {
		facing: Direction,
	},
	PumpkinStem {
		age: u8,
	},
	MelonStem {
		age: u8,
	},
	Vine {
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	GlowLichen {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		waterlogged: bool,
		west: bool,
	},
	OakFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	BrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	StoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MudBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	Mycelium {
		snowy: bool,
	},
	LilyPad,
	NetherBricks,
	NetherBrickFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	NetherBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	NetherWart {
		age: u8,
	},
	EnchantingTable,
	BrewingStand {
		has_bottle_0: bool,
		has_bottle_1: bool,
		has_bottle_2: bool,
	},
	Cauldron,
	WaterCauldron {
		level: u8,
	},
	LavaCauldron,
	PowderSnowCauldron {
		level: u8,
	},
	EndPortal,
	EndPortalFrame {
		eye: bool,
		facing: Direction,
	},
	EndStone,
	DragonEgg,
	RedstoneLamp {
		lit: bool,
	},
	Cocoa {
		age: u8,
		facing: Direction,
	},
	SandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	EmeraldOre,
	DeepslateEmeraldOre,
	EnderChest {
		facing: Direction,
		waterlogged: bool,
	},
	TripwireHook {
		attached: bool,
		facing: Direction,
		powered: bool,
	},
	Tripwire {
		attached: bool,
		disarmed: bool,
		east: bool,
		north: bool,
		powered: bool,
		south: bool,
		west: bool,
	},
	EmeraldBlock,
	SpruceStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BirchStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	JungleStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CommandBlock {
		conditional: bool,
		facing: Facing,
	},
	Beacon,
	CobblestoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MossyCobblestoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	FlowerPot,
	PottedOakSapling,
	PottedSpruceSapling,
	PottedBirchSapling,
	PottedJungleSapling,
	PottedAcaciaSapling,
	PottedDarkOakSapling,
	PottedMangrovePropagule,
	PottedFern,
	PottedDandelion,
	PottedPoppy,
	PottedBlueOrchid,
	PottedAllium,
	PottedAzureBluet,
	PottedRedTulip,
	PottedOrangeTulip,
	PottedWhiteTulip,
	PottedPinkTulip,
	PottedOxeyeDaisy,
	PottedCornflower,
	PottedLilyOfTheValley,
	PottedWitherRose,
	PottedRedMushroom,
	PottedBrownMushroom,
	PottedDeadBush,
	PottedCactus,
	Carrots {
		age: u8,
	},
	Potatoes {
		age: u8,
	},
	OakButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	SpruceButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	BirchButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	JungleButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	AcaciaButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	DarkOakButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	MangroveButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	SkeletonSkull {
		rotation: u8,
	},
	SkeletonWallSkull {
		facing: Direction,
	},
	WitherSkeletonSkull {
		rotation: u8,
	},
	WitherSkeletonWallSkull {
		facing: Direction,
	},
	ZombieHead {
		rotation: u8,
	},
	ZombieWallHead {
		facing: Direction,
	},
	PlayerHead {
		rotation: u8,
	},
	PlayerWallHead {
		facing: Direction,
	},
	CreeperHead {
		rotation: u8,
	},
	CreeperWallHead {
		facing: Direction,
	},
	DragonHead {
		rotation: u8,
	},
	DragonWallHead {
		facing: Direction,
	},
	Anvil {
		facing: Direction,
	},
	ChippedAnvil {
		facing: Direction,
	},
	DamagedAnvil {
		facing: Direction,
	},
	TrappedChest {
		facing: Direction,
		block_type: ChestType,
		waterlogged: bool,
	},
	LightWeightedPressurePlate {
		power: u8,
	},
	HeavyWeightedPressurePlate {
		power: u8,
	},
	Comparator {
		facing: Direction,
		mode: ComparatorMode,
		powered: bool,
	},
	DaylightDetector {
		inverted: bool,
		power: u8,
	},
	RedstoneBlock,
	NetherQuartzOre,
	Hopper {
		enabled: bool,
		facing: DirectionOrDown,
	},
	QuartzBlock,
	ChiseledQuartzBlock,
	QuartzPillar {
		axis: Axis3D,
	},
	QuartzStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	ActivatorRail {
		powered: bool,
		shape: StraightRailShape,
		waterlogged: bool,
	},
	Dropper {
		facing: Facing,
		triggered: bool,
	},
	WhiteTerracotta,
	OrangeTerracotta,
	MagentaTerracotta,
	LightBlueTerracotta,
	YellowTerracotta,
	LimeTerracotta,
	PinkTerracotta,
	GrayTerracotta,
	LightGrayTerracotta,
	CyanTerracotta,
	PurpleTerracotta,
	BlueTerracotta,
	BrownTerracotta,
	GreenTerracotta,
	RedTerracotta,
	BlackTerracotta,
	WhiteStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	OrangeStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	MagentaStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LightBlueStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	YellowStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LimeStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	PinkStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	GrayStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	LightGrayStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	CyanStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	PurpleStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BlueStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BrownStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	GreenStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	RedStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BlackStainedGlassPane {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	AcaciaStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DarkOakStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MangroveStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SlimeBlock,
	Barrier,
	Light {
		level: u8,
		waterlogged: bool,
	},
	IronTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	Prismarine,
	PrismarineBricks,
	DarkPrismarine,
	PrismarineStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PrismarineBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DarkPrismarineStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PrismarineSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PrismarineBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DarkPrismarineSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SeaLantern,
	HayBlock {
		axis: Axis3D,
	},
	WhiteCarpet,
	OrangeCarpet,
	MagentaCarpet,
	LightBlueCarpet,
	YellowCarpet,
	LimeCarpet,
	PinkCarpet,
	GrayCarpet,
	LightGrayCarpet,
	CyanCarpet,
	PurpleCarpet,
	BlueCarpet,
	BrownCarpet,
	GreenCarpet,
	RedCarpet,
	BlackCarpet,
	Terracotta,
	CoalBlock,
	PackedIce,
	Sunflower {
		half: UpperOrLower,
	},
	Lilac {
		half: UpperOrLower,
	},
	RoseBush {
		half: UpperOrLower,
	},
	Peony {
		half: UpperOrLower,
	},
	TallGrass {
		half: UpperOrLower,
	},
	LargeFern {
		half: UpperOrLower,
	},
	WhiteBanner {
		rotation: u8,
	},
	OrangeBanner {
		rotation: u8,
	},
	MagentaBanner {
		rotation: u8,
	},
	LightBlueBanner {
		rotation: u8,
	},
	YellowBanner {
		rotation: u8,
	},
	LimeBanner {
		rotation: u8,
	},
	PinkBanner {
		rotation: u8,
	},
	GrayBanner {
		rotation: u8,
	},
	LightGrayBanner {
		rotation: u8,
	},
	CyanBanner {
		rotation: u8,
	},
	PurpleBanner {
		rotation: u8,
	},
	BlueBanner {
		rotation: u8,
	},
	BrownBanner {
		rotation: u8,
	},
	GreenBanner {
		rotation: u8,
	},
	RedBanner {
		rotation: u8,
	},
	BlackBanner {
		rotation: u8,
	},
	WhiteWallBanner {
		facing: Direction,
	},
	OrangeWallBanner {
		facing: Direction,
	},
	MagentaWallBanner {
		facing: Direction,
	},
	LightBlueWallBanner {
		facing: Direction,
	},
	YellowWallBanner {
		facing: Direction,
	},
	LimeWallBanner {
		facing: Direction,
	},
	PinkWallBanner {
		facing: Direction,
	},
	GrayWallBanner {
		facing: Direction,
	},
	LightGrayWallBanner {
		facing: Direction,
	},
	CyanWallBanner {
		facing: Direction,
	},
	PurpleWallBanner {
		facing: Direction,
	},
	BlueWallBanner {
		facing: Direction,
	},
	BrownWallBanner {
		facing: Direction,
	},
	GreenWallBanner {
		facing: Direction,
	},
	RedWallBanner {
		facing: Direction,
	},
	BlackWallBanner {
		facing: Direction,
	},
	RedSandstone,
	ChiseledRedSandstone,
	CutRedSandstone,
	RedSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	OakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SpruceSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BirchSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	JungleSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	AcaciaSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DarkOakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MangroveSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	StoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothStoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CutSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PetrifiedOakSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CobblestoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	StoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MudBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	NetherBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	QuartzSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	RedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CutRedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PurpurSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothStone,
	SmoothSandstone,
	SmoothQuartz,
	SmoothRedSandstone,
	SpruceFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	BirchFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	JungleFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	AcaciaFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	DarkOakFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	MangroveFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	SpruceFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	BirchFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	JungleFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	AcaciaFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	DarkOakFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	MangroveFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	SpruceDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	BirchDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	JungleDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	AcaciaDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	DarkOakDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	MangroveDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	EndRod {
		facing: Facing,
	},
	ChorusPlant {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		west: bool,
	},
	ChorusFlower {
		age: u8,
	},
	PurpurBlock,
	PurpurPillar {
		axis: Axis3D,
	},
	PurpurStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	EndStoneBricks,
	Beetroots {
		age: u8,
	},
	DirtPath,
	EndGateway,
	RepeatingCommandBlock {
		conditional: bool,
		facing: Facing,
	},
	ChainCommandBlock {
		conditional: bool,
		facing: Facing,
	},
	FrostedIce {
		age: u8,
	},
	MagmaBlock,
	NetherWartBlock,
	RedNetherBricks,
	BoneBlock {
		axis: Axis3D,
	},
	StructureVoid,
	Observer {
		facing: Facing,
		powered: bool,
	},
	ShulkerBox {
		facing: Facing,
	},
	WhiteShulkerBox {
		facing: Facing,
	},
	OrangeShulkerBox {
		facing: Facing,
	},
	MagentaShulkerBox {
		facing: Facing,
	},
	LightBlueShulkerBox {
		facing: Facing,
	},
	YellowShulkerBox {
		facing: Facing,
	},
	LimeShulkerBox {
		facing: Facing,
	},
	PinkShulkerBox {
		facing: Facing,
	},
	GrayShulkerBox {
		facing: Facing,
	},
	LightGrayShulkerBox {
		facing: Facing,
	},
	CyanShulkerBox {
		facing: Facing,
	},
	PurpleShulkerBox {
		facing: Facing,
	},
	BlueShulkerBox {
		facing: Facing,
	},
	BrownShulkerBox {
		facing: Facing,
	},
	GreenShulkerBox {
		facing: Facing,
	},
	RedShulkerBox {
		facing: Facing,
	},
	BlackShulkerBox {
		facing: Facing,
	},
	WhiteGlazedTerracotta {
		facing: Direction,
	},
	OrangeGlazedTerracotta {
		facing: Direction,
	},
	MagentaGlazedTerracotta {
		facing: Direction,
	},
	LightBlueGlazedTerracotta {
		facing: Direction,
	},
	YellowGlazedTerracotta {
		facing: Direction,
	},
	LimeGlazedTerracotta {
		facing: Direction,
	},
	PinkGlazedTerracotta {
		facing: Direction,
	},
	GrayGlazedTerracotta {
		facing: Direction,
	},
	LightGrayGlazedTerracotta {
		facing: Direction,
	},
	CyanGlazedTerracotta {
		facing: Direction,
	},
	PurpleGlazedTerracotta {
		facing: Direction,
	},
	BlueGlazedTerracotta {
		facing: Direction,
	},
	BrownGlazedTerracotta {
		facing: Direction,
	},
	GreenGlazedTerracotta {
		facing: Direction,
	},
	RedGlazedTerracotta {
		facing: Direction,
	},
	BlackGlazedTerracotta {
		facing: Direction,
	},
	WhiteConcrete,
	OrangeConcrete,
	MagentaConcrete,
	LightBlueConcrete,
	YellowConcrete,
	LimeConcrete,
	PinkConcrete,
	GrayConcrete,
	LightGrayConcrete,
	CyanConcrete,
	PurpleConcrete,
	BlueConcrete,
	BrownConcrete,
	GreenConcrete,
	RedConcrete,
	BlackConcrete,
	WhiteConcretePowder,
	OrangeConcretePowder,
	MagentaConcretePowder,
	LightBlueConcretePowder,
	YellowConcretePowder,
	LimeConcretePowder,
	PinkConcretePowder,
	GrayConcretePowder,
	LightGrayConcretePowder,
	CyanConcretePowder,
	PurpleConcretePowder,
	BlueConcretePowder,
	BrownConcretePowder,
	GreenConcretePowder,
	RedConcretePowder,
	BlackConcretePowder,
	Kelp {
		age: u8,
	},
	KelpPlant,
	DriedKelpBlock,
	TurtleEgg {
		eggs: u8,
		hatch: u8,
	},
	DeadTubeCoralBlock,
	DeadBrainCoralBlock,
	DeadBubbleCoralBlock,
	DeadFireCoralBlock,
	DeadHornCoralBlock,
	TubeCoralBlock,
	BrainCoralBlock,
	BubbleCoralBlock,
	FireCoralBlock,
	HornCoralBlock,
	DeadTubeCoral {
		waterlogged: bool,
	},
	DeadBrainCoral {
		waterlogged: bool,
	},
	DeadBubbleCoral {
		waterlogged: bool,
	},
	DeadFireCoral {
		waterlogged: bool,
	},
	DeadHornCoral {
		waterlogged: bool,
	},
	TubeCoral {
		waterlogged: bool,
	},
	BrainCoral {
		waterlogged: bool,
	},
	BubbleCoral {
		waterlogged: bool,
	},
	FireCoral {
		waterlogged: bool,
	},
	HornCoral {
		waterlogged: bool,
	},
	DeadTubeCoralFan {
		waterlogged: bool,
	},
	DeadBrainCoralFan {
		waterlogged: bool,
	},
	DeadBubbleCoralFan {
		waterlogged: bool,
	},
	DeadFireCoralFan {
		waterlogged: bool,
	},
	DeadHornCoralFan {
		waterlogged: bool,
	},
	TubeCoralFan {
		waterlogged: bool,
	},
	BrainCoralFan {
		waterlogged: bool,
	},
	BubbleCoralFan {
		waterlogged: bool,
	},
	FireCoralFan {
		waterlogged: bool,
	},
	HornCoralFan {
		waterlogged: bool,
	},
	DeadTubeCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadBrainCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadBubbleCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadFireCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	DeadHornCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	TubeCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	BrainCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	BubbleCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	FireCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	HornCoralWallFan {
		facing: Direction,
		waterlogged: bool,
	},
	SeaPickle {
		pickles: u8,
		waterlogged: bool,
	},
	BlueIce,
	Conduit {
		waterlogged: bool,
	},
	BambooSapling,
	Bamboo {
		age: u8,
		leaves: Leaves,
		stage: u8,
	},
	PottedBamboo,
	VoidAir,
	CaveAir,
	BubbleColumn {
		drag: bool,
	},
	PolishedGraniteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothRedSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MossyStoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedDioriteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	MossyCobblestoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	EndStoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	StoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothSandstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	SmoothQuartzStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	GraniteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	AndesiteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	RedNetherBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedAndesiteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DioriteStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedGraniteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothRedSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MossyStoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedDioriteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	MossyCobblestoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	EndStoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothSandstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	SmoothQuartzSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	GraniteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	AndesiteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	RedNetherBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedAndesiteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DioriteSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	BrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	PrismarineWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	RedSandstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MossyStoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	GraniteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	StoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	MudBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	NetherBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	AndesiteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	RedNetherBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	SandstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	EndStoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	DioriteWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	Scaffolding {
		bottom: bool,
		distance: u8,
		waterlogged: bool,
	},
	Loom {
		facing: Direction,
	},
	Barrel {
		facing: Facing,
		open: bool,
	},
	Smoker {
		facing: Direction,
		lit: bool,
	},
	BlastFurnace {
		facing: Direction,
		lit: bool,
	},
	CartographyTable,
	FletchingTable,
	Grindstone {
		face: Face,
		facing: Direction,
	},
	Lectern {
		facing: Direction,
		has_book: bool,
		powered: bool,
	},
	SmithingTable,
	Stonecutter {
		facing: Direction,
	},
	Bell {
		attachment: Attachment,
		facing: Direction,
		powered: bool,
	},
	Lantern {
		hanging: bool,
		waterlogged: bool,
	},
	SoulLantern {
		hanging: bool,
		waterlogged: bool,
	},
	Campfire {
		facing: Direction,
		lit: bool,
		signal_fire: bool,
		waterlogged: bool,
	},
	SoulCampfire {
		facing: Direction,
		lit: bool,
		signal_fire: bool,
		waterlogged: bool,
	},
	SweetBerryBush {
		age: u8,
	},
	WarpedStem {
		axis: Axis3D,
	},
	StrippedWarpedStem {
		axis: Axis3D,
	},
	WarpedHyphae {
		axis: Axis3D,
	},
	StrippedWarpedHyphae {
		axis: Axis3D,
	},
	WarpedNylium,
	WarpedFungus,
	WarpedWartBlock,
	WarpedRoots,
	NetherSprouts,
	CrimsonStem {
		axis: Axis3D,
	},
	StrippedCrimsonStem {
		axis: Axis3D,
	},
	CrimsonHyphae {
		axis: Axis3D,
	},
	StrippedCrimsonHyphae {
		axis: Axis3D,
	},
	CrimsonNylium,
	CrimsonFungus,
	Shroomlight,
	WeepingVines {
		age: u8,
	},
	WeepingVinesPlant,
	TwistingVines {
		age: u8,
	},
	TwistingVinesPlant,
	CrimsonRoots,
	CrimsonPlanks,
	WarpedPlanks,
	CrimsonSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WarpedSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CrimsonPressurePlate {
		powered: bool,
	},
	WarpedPressurePlate {
		powered: bool,
	},
	CrimsonFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	WarpedFence {
		east: bool,
		north: bool,
		south: bool,
		waterlogged: bool,
		west: bool,
	},
	CrimsonTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	WarpedTrapdoor {
		facing: Direction,
		half: Half,
		open: bool,
		powered: bool,
		waterlogged: bool,
	},
	CrimsonFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	WarpedFenceGate {
		facing: Direction,
		in_wall: bool,
		open: bool,
		powered: bool,
	},
	CrimsonStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WarpedStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CrimsonButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	WarpedButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	CrimsonDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	WarpedDoor {
		facing: Direction,
		half: UpperOrLower,
		hinge: Hinge,
		open: bool,
		powered: bool,
	},
	CrimsonSign {
		rotation: u8,
		waterlogged: bool,
	},
	WarpedSign {
		rotation: u8,
		waterlogged: bool,
	},
	CrimsonWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	WarpedWallSign {
		facing: Direction,
		waterlogged: bool,
	},
	StructureBlock {
		mode: StructureBlockMode,
	},
	Jigsaw {
		orientation: Orientation,
	},
	Composter {
		level: u8,
	},
	Target {
		power: u8,
	},
	BeeNest {
		facing: Direction,
		honey_level: u8,
	},
	Beehive {
		facing: Direction,
		honey_level: u8,
	},
	HoneyBlock,
	HoneycombBlock,
	NetheriteBlock,
	AncientDebris,
	CryingObsidian,
	RespawnAnchor {
		charges: u8,
	},
	PottedCrimsonFungus,
	PottedWarpedFungus,
	PottedCrimsonRoots,
	PottedWarpedRoots,
	Lodestone,
	Blackstone,
	BlackstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	BlackstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	BlackstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedBlackstone,
	PolishedBlackstoneBricks,
	CrackedPolishedBlackstoneBricks,
	ChiseledPolishedBlackstone,
	PolishedBlackstoneBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedBlackstoneBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedBlackstoneBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	GildedBlackstone,
	PolishedBlackstoneStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedBlackstoneSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedBlackstonePressurePlate {
		powered: bool,
	},
	PolishedBlackstoneButton {
		face: Face,
		facing: Direction,
		powered: bool,
	},
	PolishedBlackstoneWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	ChiseledNetherBricks,
	CrackedNetherBricks,
	QuartzBricks,
	Candle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	WhiteCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	OrangeCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	MagentaCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LightBlueCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	YellowCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LimeCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	PinkCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	GrayCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	LightGrayCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	CyanCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	PurpleCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BlueCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BrownCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	GreenCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	RedCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	BlackCandle {
		candles: u8,
		lit: bool,
		waterlogged: bool,
	},
	CandleCake {
		lit: bool,
	},
	WhiteCandleCake {
		lit: bool,
	},
	OrangeCandleCake {
		lit: bool,
	},
	MagentaCandleCake {
		lit: bool,
	},
	LightBlueCandleCake {
		lit: bool,
	},
	YellowCandleCake {
		lit: bool,
	},
	LimeCandleCake {
		lit: bool,
	},
	PinkCandleCake {
		lit: bool,
	},
	GrayCandleCake {
		lit: bool,
	},
	LightGrayCandleCake {
		lit: bool,
	},
	CyanCandleCake {
		lit: bool,
	},
	PurpleCandleCake {
		lit: bool,
	},
	BlueCandleCake {
		lit: bool,
	},
	BrownCandleCake {
		lit: bool,
	},
	GreenCandleCake {
		lit: bool,
	},
	RedCandleCake {
		lit: bool,
	},
	BlackCandleCake {
		lit: bool,
	},
	AmethystBlock,
	BuddingAmethyst,
	AmethystCluster {
		facing: Facing,
		waterlogged: bool,
	},
	LargeAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	MediumAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	SmallAmethystBud {
		facing: Facing,
		waterlogged: bool,
	},
	Tuff,
	Calcite,
	TintedGlass,
	PowderSnow,
	SculkSensor {
		power: u8,
		sculk_sensor_phase: SculkSensorPhase,
		waterlogged: bool,
	},
	Sculk,
	SculkVein {
		down: bool,
		east: bool,
		north: bool,
		south: bool,
		up: bool,
		waterlogged: bool,
		west: bool,
	},
	SculkCatalyst {
		bloom: bool,
	},
	SculkShrieker {
		can_summon: bool,
		shrieking: bool,
		waterlogged: bool,
	},
	OxidizedCopper,
	WeatheredCopper,
	ExposedCopper,
	CopperBlock,
	CopperOre,
	DeepslateCopperOre,
	OxidizedCutCopper,
	WeatheredCutCopper,
	ExposedCutCopper,
	CutCopper,
	OxidizedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WeatheredCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	ExposedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	OxidizedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WeatheredCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	ExposedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedCopperBlock,
	WaxedWeatheredCopper,
	WaxedExposedCopper,
	WaxedOxidizedCopper,
	WaxedOxidizedCutCopper,
	WaxedWeatheredCutCopper,
	WaxedExposedCutCopper,
	WaxedCutCopper,
	WaxedOxidizedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedWeatheredCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedExposedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedCutCopperStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	WaxedOxidizedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedWeatheredCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedExposedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	WaxedCutCopperSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	LightningRod {
		facing: Facing,
		powered: bool,
		waterlogged: bool,
	},
	PointedDripstone {
		thickness: Thickness,
		vertical_direction: VerticalDirection,
		waterlogged: bool,
	},
	DripstoneBlock,
	CaveVines {
		age: u8,
		berries: bool,
	},
	CaveVinesPlant {
		berries: bool,
	},
	SporeBlossom,
	Azalea,
	FloweringAzalea,
	MossCarpet,
	MossBlock,
	BigDripleaf {
		facing: Direction,
		tilt: Tilt,
		waterlogged: bool,
	},
	BigDripleafStem {
		facing: Direction,
		waterlogged: bool,
	},
	SmallDripleaf {
		facing: Direction,
		half: UpperOrLower,
		waterlogged: bool,
	},
	HangingRoots {
		waterlogged: bool,
	},
	RootedDirt,
	Mud,
	Deepslate {
		axis: Axis3D,
	},
	CobbledDeepslate,
	CobbledDeepslateStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	CobbledDeepslateSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	CobbledDeepslateWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	PolishedDeepslate,
	PolishedDeepslateStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	PolishedDeepslateSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	PolishedDeepslateWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	DeepslateTiles,
	DeepslateTileStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DeepslateTileSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DeepslateTileWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	DeepslateBricks,
	DeepslateBrickStairs {
		facing: Direction,
		half: Half,
		shape: StairShape,
		waterlogged: bool,
	},
	DeepslateBrickSlab {
		block_type: SlabType,
		waterlogged: bool,
	},
	DeepslateBrickWall {
		east: WallConnection,
		north: WallConnection,
		south: WallConnection,
		up: bool,
		waterlogged: bool,
		west: WallConnection,
	},
	ChiseledDeepslate,
	CrackedDeepslateBricks,
	CrackedDeepslateTiles,
	InfestedDeepslate {
		axis: Axis3D,
	},
	SmoothBasalt,
	RawIronBlock,
	RawCopperBlock,
	RawGoldBlock,
	PottedAzaleaBush,
	PottedFloweringAzaleaBush,
	OchreFroglight {
		axis: Axis3D,
	},
	VerdantFroglight {
		axis: Axis3D,
	},
	PearlescentFroglight {
		axis: Axis3D,
	},
	Frogspawn,
	ReinforcedDeepslate,
}

