// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs

use crate::fluid_parameter::*;

include!(concat!(env!("OUT_DIR"), "/fluid_state_to_u16.rs"));
include!(concat!(env!("OUT_DIR"), "/u16_to_fluid_state.rs"));
include!(concat!(env!("OUT_DIR"), "/set_fluid_property.rs"));
include!(concat!(env!("OUT_DIR"), "/fluid_state_id_to_fluid.rs"));
include!(concat!(env!("OUT_DIR"), "/fluid_attribute_lut.rs"));

pub fn state_to_fluid(id: u16) -> Result<Fluid, NoSuchFluidError> {
	if id >= FLUID_STATE_ID_TO_FLUID.len() as _ { return Err(NoSuchFluidError(id)); }
	Ok(FLUID_STATE_ID_TO_FLUID[id as usize])
}

#[derive(Debug)]
pub struct FluidAttributes {
	pub own_height: f32,
	pub amount: u8,
	pub is_source: bool,
}

#[derive(Debug, thiserror::Error)]
#[error("No fluid exists for id: {0}")]
pub struct NoSuchFluidError(u16);

impl FluidAttributes {
    pub fn from_fluid_state(mut id: u16) -> &'static FluidAttributes {
        if id >= FLUID_ATTRIBUTE_INDEX_LUT.len() as _ {
            id = 0;
        }
        &FLUID_ATTRIBUTES_LUT[FLUID_ATTRIBUTE_INDEX_LUT[id as usize] as usize]
    }
}

#[derive(Debug, Copy, Clone)]
pub enum FluidState {
	Empty {},
	FlowingWater {
		falling: bool,
		level: u8,
	},
	Water {
		falling: bool,
	},
	FlowingLava {
		falling: bool,
		level: u8,
	},
	Lava {
		falling: bool,
	},
}

#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[repr(u16)]
pub enum Fluid {
	Empty = 0,
	FlowingWater = 1,
	Water = 2,
	FlowingLava = 3,
	Lava = 4,
}

