// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs

#![allow(dead_code)]
#![allow(unused_imports)]

pub mod block;
pub mod block_parameter;
pub mod fluid;
pub mod fluid_parameter;
pub mod entity;
pub mod particle;
pub mod item;
pub mod builtin;
pub mod types;
pub mod font_width;