// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs
// Data is provided courtesy of `https://github.com/Minestom/MinestomDataGenerator`

#![allow(dead_code)]
#![allow(unused_imports)]

pub mod block;
pub mod block_parameter;
pub mod entity;
pub mod item;
pub mod placement;
pub mod tags;