// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs

use graphite_binary::slice_serialization::*;
slice_serializable! {
	#[derive(Debug, Clone)]
	pub enum Particle {
		AngryVillager,
		Block {
			block_state: u16 as VarInt,
		},
		BlockMarker {
			block_state: u16 as VarInt,
		},
		Bubble,
		Cloud,
		Crit,
		DamageIndicator,
		DragonBreath,
		DrippingLava,
		FallingLava,
		LandingLava,
		DrippingWater,
		FallingWater,
		Dust {
			color: i32 as BigEndian,
			scale: f32 as BigEndian,
		},
		DustColorTransition {
			from_color: i32 as BigEndian,
			to_color: i32 as BigEndian,
			scale: f32 as BigEndian,
		},
		Effect,
		ElderGuardian,
		EnchantedHit,
		Enchant,
		EndRod,
		EntityEffect {
			color: i32 as BigEndian,
		},
		ExplosionEmitter,
		Explosion,
		Gust,
		SmallGust,
		GustEmitterLarge,
		GustEmitterSmall,
		SonicBoom,
		FallingDust {
			block_state: u16 as VarInt,
		},
		Firework,
		Fishing,
		Flame,
		Infested,
		CherryLeaves,
		PaleOakLeaves,
		TintedLeaves {
			color: i32 as BigEndian,
		},
		SculkSoul,
		SculkCharge {
			roll: f32 as BigEndian,
		},
		SculkChargePop,
		SoulFireFlame,
		Soul,
		Flash,
		HappyVillager,
		Composter,
		Heart,
		InstantEffect,
		Item {
			encoded_item: Box<[u8]> as WriteOnlyBlob,
		},
		Vibration {
			destination: PositionSource,
			arrival_in_ticks: i32 as BigEndian,
		},
		Trail {
			target_x: f64 as BigEndian,
			target_y: f64 as BigEndian,
			target_z: f64 as BigEndian,
			color: i32 as BigEndian,
			duration: i32 as VarInt,
		},
		ItemSlime,
		ItemCobweb,
		ItemSnowball,
		LargeSmoke,
		Lava,
		Mycelium,
		Note,
		Poof,
		Portal,
		Rain,
		Smoke,
		WhiteSmoke,
		Sneeze,
		Spit,
		SquidInk,
		SweepAttack,
		TotemOfUndying,
		Underwater,
		Splash,
		Witch,
		BubblePop,
		CurrentDown,
		BubbleColumnUp,
		Nautilus,
		Dolphin,
		CampfireCosySmoke,
		CampfireSignalSmoke,
		DrippingHoney,
		FallingHoney,
		LandingHoney,
		FallingNectar,
		FallingSporeBlossom,
		Ash,
		CrimsonSpore,
		WarpedSpore,
		SporeBlossomAir,
		DrippingObsidianTear,
		FallingObsidianTear,
		LandingObsidianTear,
		ReversePortal,
		WhiteAsh,
		SmallFlame,
		Snowflake,
		DrippingDripstoneLava,
		FallingDripstoneLava,
		DrippingDripstoneWater,
		FallingDripstoneWater,
		GlowSquidInk,
		Glow,
		WaxOn,
		WaxOff,
		ElectricSpark,
		Scrape,
		Shriek {
			delay: i32 as VarInt,
		},
		EggCrack,
		DustPlume,
		TrialSpawnerDetection,
		TrialSpawnerDetectionOminous,
		VaultConnection,
		DustPillar {
			block_state: u16 as VarInt,
		},
		OminousSpawning,
		RaidOmen,
		TrialOmen,
		BlockCrumble {
			block_state: u16 as VarInt,
		},
		Firefly,
	}
}


#[derive(Debug, Copy, Clone)]
pub enum PositionSource {
    Block { // Encoded as a long
        x: i32,
        y: i32,
        z: i32,
    },
    Entity {
        id: i32, // VarInt
        y_offset: f32, 
    }
}

impl <'r, 'd: 'r> SliceSerializable<'r, 'd> for PositionSource {
    type CopyType = PositionSource;

    #[inline(always)]
    fn as_copy_type(t: &'r PositionSource) -> Self::CopyType {
        *t
    }

    fn read(_: &mut &'d [u8]) -> anyhow::Result<PositionSource> {
        todo!("reading positionsource unimplemented")
    }

    unsafe fn write(mut bytes: &mut [u8], data: Self::CopyType) -> &mut [u8] {
        match data {
            PositionSource::Block { x, y, z } => {
                bytes = <Single as SliceSerializable<u8>>::write(bytes, crate::builtin::PositionSourceType::Block as u8);
                
                let packed_position = ((x as i64 & 0x3FFFFFF) << 38)
                    | ((z as i64 & 0x3FFFFFF) << 12)
                    | (y as i64 & 0xFFF);
                bytes = <BigEndian as SliceSerializable<i64>>::write(bytes, packed_position);

            },
            PositionSource::Entity { id, y_offset } => {
                bytes = <Single as SliceSerializable<u8>>::write(bytes, crate::builtin::PositionSourceType::Entity as u8);
                bytes = <VarInt as SliceSerializable<i32>>::write(bytes, id);
                bytes = <BigEndian as SliceSerializable<f32>>::write(bytes, y_offset);
            },
        }
        bytes
    }

    fn get_write_size(data: Self::CopyType) -> usize {
        let mut write_size = 0;
        match data {
            PositionSource::Block { x, y, z } => {
                write_size += <Single as SliceSerializable<u8>>::get_write_size(crate::builtin::PositionSourceType::Block as u8);
                write_size += <BigEndian as SliceSerializable<i64>>::get_write_size(0)

            },
            PositionSource::Entity { id, y_offset } => {
                write_size += <Single as SliceSerializable<u8>>::get_write_size(crate::builtin::PositionSourceType::Entity as u8);
                write_size += <VarInt as SliceSerializable<i32>>::get_write_size(id);
                write_size += <BigEndian as SliceSerializable<f32>>::get_write_size(y_offset);
            },
        }
        write_size
    }
}
