// DO NOT MANUALLY EDIT THIS FILE
// This file has been autogenerated by minecraft_constants/build.rs

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum AdvancementType {
	#[default]
	Task = 0,
	Challenge = 1,
	Goal = 2,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ArmadilloState {
	#[default]
	Idle = 0,
	Rolling = 1,
	Scared = 2,
	Unrolling = 3,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum BossBarColor {
	#[default]
	Pink = 0,
	Blue = 1,
	Red = 2,
	Green = 3,
	Yellow = 4,
	Purple = 5,
	White = 6,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum BossBarOverlay {
	#[default]
	Progress = 0,
	Notched6 = 1,
	Notched10 = 2,
	Notched12 = 3,
	Notched20 = 4,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ChatVisibility {
	#[default]
	Full = 0,
	System = 1,
	Hidden = 2,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ClickType {
	#[default]
	Pickup = 0,
	QuickMove = 1,
	Swap = 2,
	Clone = 3,
	Throw = 4,
	QuickCraft = 5,
	PickupAll = 6,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum Direction {
	#[default]
	Down = 0,
	Up = 1,
	North = 2,
	South = 3,
	West = 4,
	East = 5,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum DisplaySlot {
	#[default]
	List = 0,
	Sidebar = 1,
	BelowName = 2,
	SidebarTeamBlack = 3,
	SidebarTeamDarkBlue = 4,
	SidebarTeamDarkGreen = 5,
	SidebarTeamDarkAqua = 6,
	SidebarTeamDarkRed = 7,
	SidebarTeamDarkPurple = 8,
	SidebarTeamGold = 9,
	SidebarTeamGray = 10,
	SidebarTeamDarkGray = 11,
	SidebarTeamBlue = 12,
	SidebarTeamGreen = 13,
	SidebarTeamAqua = 14,
	SidebarTeamRed = 15,
	SidebarTeamLightPurple = 16,
	SidebarTeamYellow = 17,
	SidebarTeamWhite = 18,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum DyeColor {
	#[default]
	White = 0,
	Orange = 1,
	Magenta = 2,
	LightBlue = 3,
	Yellow = 4,
	Lime = 5,
	Pink = 6,
	Gray = 7,
	LightGray = 8,
	Cyan = 9,
	Purple = 10,
	Blue = 11,
	Brown = 12,
	Green = 13,
	Red = 14,
	Black = 15,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum EquipmentSlot {
	#[default]
	Mainhand = 0,
	Offhand = 5,
	Feet = 1,
	Legs = 2,
	Chest = 3,
	Head = 4,
	Body = 6,
	Saddle = 7,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum HumanoidArm {
	#[default]
	Left = 0,
	Right = 1,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum InteractionHand {
	#[default]
	MainHand = 0,
	OffHand = 1,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum MapPostProcessing {
	#[default]
	Lock = 0,
	Scale = 1,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum MoveAction {
	#[default]
	PressShiftKey = 0,
	ReleaseShiftKey = 1,
	StopSleeping = 2,
	StartSprinting = 3,
	StopSprinting = 4,
	StartRidingJump = 5,
	StopRidingJump = 6,
	OpenInventory = 7,
	StartFallFlying = 8,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum HandAction {
	#[default]
	StartDestroyBlock = 0,
	AbortDestroyBlock = 1,
	StopDestroyBlock = 2,
	DropAllItems = 3,
	DropItem = 4,
	ReleaseUseItem = 5,
	SwapItemWithOffhand = 6,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum PlayerListAction {
	#[default]
	AddPlayer = 0,
	InitializeChat = 1,
	UpdateGameMode = 2,
	UpdateListed = 3,
	UpdateLatency = 4,
	UpdateDisplayName = 5,
	UpdateListOrder = 6,
	UpdateHat = 7,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ObjectiveRenderType {
	#[default]
	Integer = 0,
	Hearts = 1,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ParticleStatus {
	#[default]
	All = 0,
	Decreased = 1,
	Minimal = 2,
}

#[derive(Debug, enumset::EnumSetType)]
#[repr(u8)]
pub enum RelativeMovement {
	X = 0,
	Y = 1,
	Z = 2,
	YRot = 3,
	XRot = 4,
	DeltaX = 5,
	DeltaY = 6,
	DeltaZ = 7,
	RotateDelta = 8,
}

impl RelativeMovement {
	pub const POSITION: enumset::EnumSet<Self> = enumset::enum_set_union!(Self::X, Self::Y, Self::Z);
	pub const ROTATION: enumset::EnumSet<Self> = enumset::enum_set_union!(Self::XRot, Self::YRot);
	pub const VELOCITY: enumset::EnumSet<Self> = enumset::enum_set_union!(Self::DeltaX, Self::DeltaY, Self::DeltaZ);
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum Pose {
	#[default]
	Standing = 0,
	FallFlying = 1,
	Sleeping = 2,
	Swimming = 3,
	SpinAttack = 4,
	Crouching = 5,
	LongJumping = 6,
	Dying = 7,
	Croaking = 8,
	UsingTongue = 9,
	Sitting = 10,
	Roaring = 11,
	Sniffing = 12,
	Emerging = 13,
	Digging = 14,
	Sliding = 15,
	Shooting = 16,
	Inhaling = 17,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum Rarity {
	#[default]
	Common = 0,
	Uncommon = 1,
	Rare = 2,
	Epic = 3,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum SnifferState {
	#[default]
	Idling = 0,
	FeelingHappy = 1,
	Scenting = 2,
	Sniffing = 3,
	Searching = 4,
	Digging = 5,
	Rising = 6,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum SoundSource {
	#[default]
	Master = 0,
	Music = 1,
	Records = 2,
	Weather = 3,
	Blocks = 4,
	Hostile = 5,
	Neutral = 6,
	Players = 7,
	Ambient = 8,
	Voice = 9,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ItemUseAnimation {
	#[default]
	None = 0,
	Eat = 1,
	Drink = 2,
	Block = 3,
	Bow = 4,
	Spear = 5,
	Crossbow = 6,
	Spyglass = 7,
	TootHorn = 8,
	Brush = 9,
	Bundle = 10,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum ClientAction {
	#[default]
	PerformRespawn = 0,
	RequestStats = 1,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum BillboardConstraint {
	#[default]
	Fixed = 0,
	Vertical = 1,
	Horizontal = 2,
	Center = 3,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum EntityAnimation {
	#[default]
	SwingMainHand = 0,
	WakeUp = 2,
	SwingOffHand = 3,
	CriticalHit = 4,
	MagicCriticalHit = 5,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(i32)]
pub enum LevelEvent {
	#[default]
	SoundDispenserDispense = 1000,
	SoundDispenserFail = 1001,
	SoundDispenserProjectileLaunch = 1002,
	SoundFireworkShoot = 1004,
	SoundExtinguishFire = 1009,
	SoundPlayJukeboxSong = 1010,
	SoundStopJukeboxSong = 1011,
	SoundGhastWarning = 1015,
	SoundGhastFireball = 1016,
	SoundDragonFireball = 1017,
	SoundBlazeFireball = 1018,
	SoundZombieWoodenDoor = 1019,
	SoundZombieIronDoor = 1020,
	SoundZombieDoorCrash = 1021,
	SoundWitherBlockBreak = 1022,
	SoundWitherBossSpawn = 1023,
	SoundWitherBossShoot = 1024,
	SoundBatLiftoff = 1025,
	SoundZombieInfected = 1026,
	SoundZombieConverted = 1027,
	SoundDragonDeath = 1028,
	SoundAnvilBroken = 1029,
	SoundAnvilUsed = 1030,
	SoundAnvilLand = 1031,
	SoundPortalTravel = 1032,
	SoundChorusGrow = 1033,
	SoundChorusDeath = 1034,
	SoundBrewingStandBrew = 1035,
	SoundEndPortalSpawn = 1038,
	SoundPhantomBite = 1039,
	SoundZombieToDrowned = 1040,
	SoundHuskToZombie = 1041,
	SoundGrindstoneUsed = 1042,
	SoundPageTurn = 1043,
	SoundSmithingTableUsed = 1044,
	SoundPointedDripstoneLand = 1045,
	SoundDripLavaIntoCauldron = 1046,
	SoundDripWaterIntoCauldron = 1047,
	SoundSkeletonToStray = 1048,
	SoundCrafterCraft = 1049,
	SoundCrafterFail = 1050,
	SoundWindChargeShoot = 1051,
	ComposterFill = 1500,
	LavaFizz = 1501,
	RedstoneTorchBurnout = 1502,
	EndPortalFrameFill = 1503,
	DripstoneDrip = 1504,
	ParticlesAndSoundPlantGrowth = 1505,
	ParticlesShootSmoke = 2000,
	ParticlesDestroyBlock = 2001,
	ParticlesSpellPotionSplash = 2002,
	ParticlesEyeOfEnderDeath = 2003,
	ParticlesMobblockSpawn = 2004,
	ParticlesDragonFireballSplash = 2006,
	ParticlesInstantPotionSplash = 2007,
	ParticlesDragonBlockBreak = 2008,
	ParticlesWaterEvaporating = 2009,
	ParticlesShootWhiteSmoke = 2010,
	ParticlesBeeGrowth = 2011,
	ParticlesTurtleEggPlacement = 2012,
	ParticlesSmashAttack = 2013,
	AnimationEndGatewaySpawn = 3000,
	AnimationDragonSummonRoar = 3001,
	ParticlesElectricSpark = 3002,
	ParticlesAndSoundWaxOn = 3003,
	ParticlesWaxOff = 3004,
	ParticlesScrape = 3005,
	ParticlesSculkCharge = 3006,
	ParticlesSculkShriek = 3007,
	ParticlesAndSoundBrushBlockComplete = 3008,
	ParticlesEggCrack = 3009,
	ParticlesTrialSpawnerSpawn = 3011,
	ParticlesTrialSpawnerSpawnMobAt = 3012,
	ParticlesTrialSpawnerDetectPlayer = 3013,
	AnimationTrialSpawnerEjectItem = 3014,
	AnimationVaultActivate = 3015,
	AnimationVaultDeactivate = 3016,
	AnimationVaultEjectItem = 3017,
	AnimationSpawnCobweb = 3018,
	ParticlesTrialSpawnerDetectPlayerOminous = 3019,
	ParticlesTrialSpawnerBecomeOminous = 3020,
	ParticlesTrialSpawnerSpawnItem = 3021,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Default, strum_macros::IntoStaticStr, num_enum::TryFromPrimitive, num_enum::IntoPrimitive)]
#[strum(serialize_all = "snake_case")]
#[repr(u8)]
pub enum GameEvent {
	#[default]
	NoRespawnBlockAvailable = 0,
	StartRaining = 1,
	StopRaining = 2,
	ChangeGameMode = 3,
	WinGame = 4,
	DemoEvent = 5,
	PlayArrowHitSound = 6,
	RainLevelChange = 7,
	ThunderLevelChange = 8,
	PufferFishSting = 9,
	GuardianElderEffect = 10,
	ImmediateRespawn = 11,
	LimitedCrafting = 12,
	LevelChunksLoadStart = 13,
}

