use glam::DVec3;
use graphite_binary::nbt::NBT;
use graphite_mc_constants::{item::Item};

pub enum Particle {
    AmbientEntityEffect,
    AngryVillager,
    Block {
        // block: Block
        block: u8
    },
    BlockMarker {
        // block: Block
        block: u8
    },
    Bubble,
    Cloud,
    Crit,
    DamageIndicator,
    DragonBreath,
    DrippingLava,
    FallingLava,
    LandingLava,
    DrippingWater,
    FallingWater,
    Dust {
        red: f32,
        green: f32,
        blue: f32,
        scale: f32
    },
    DustColorTransition {
        from_red: f32,
        from_green: f32,
        from_blue: f32,
        to_red: f32,
        to_green: f32,
        to_blue: f32,
        scale: f32
    },
    Effect,
    ElderGuardian,
    EnchantedHit,
    Enchant,
    EndRod,
    EntityEffect,
    ExplosionEmitter,
    Explosion,
    Gust,
    GustEmitter,
    SonicBoom,
    FallingDust {
        // block: Block
        block: u8
    },
    Firework,
    Fishing,
    Flame,
    CherryLeaves,
    SculkSoul,
    SculkCharge,
    SculkChargePop,
    SoulFireFlame,
    Soul,
    Flash,
    HappyVillager,
    Composter,
    Heart,
    InstantEffect,
    Item {
        item: Item,
        nbt: Option<NBT>
    },
    Vibration {
        destination: DVec3,
        arrival_in_ticks: i32
    },
    ItemSlime,
    ItemSnowball,
    LargeSmoke,
    Lava,
    Mycelium,
    Note,
    Poof,
    Portal,
    Rain,
    Smoke,
    WhiteSmoke,
    Sneeze,
    Spit,
    SquidInk,
    SweepAttack,
    TotemOfUndying,
    Underwater,
    Splash,
    Witch,
    BubblePop,
    CurrentDown,
    BubbleColumnUp,
    Nautilus,
    Dolphin,
    CampfireCosySmoke,
    CampfireSignalSmoke,
    DrippingHoney,
    FallingHoney,
    LandingHoney,
    FallingNectar,
    FallingSporeBlossom,
    Ash,
    CrimsonSpore,
    WarpedSpore,
    SporeBlossomAir,
    DrippingObsidianTear,
    FallingObsidianTear,
    LandingObsidianTear,
    ReversePortal,
    WhiteAsh,
    SmallFlame,
    Snowflake,
    DrippingDripstoneLava,
    FallingDripstoneLava,
    DrippingDripstoneWater,
    FallingDripstoneWater,
    GlowSquidInk,
    Glow,
    WaxOn,
    WaxOff,
    ElectricSpark,
    Scrape,
    Shriek {
        delay: i32,
    },
    EggCrack,
    DustPlume,
    GustDust,
    TrialSpawnerDetection
}

impl Particle {
    pub const fn get_id(&self) -> i32 {
        match self {
            Particle::AmbientEntityEffect => 0,
            Particle::AngryVillager => 1,
            Particle::Block { block: _ } => 2,
            Particle::BlockMarker { block: _ } => 3,
            Particle::Bubble => 4,
            Particle::Cloud => 5,
            Particle::Crit => 6,
            Particle::DamageIndicator => 7,
            Particle::DragonBreath => 8,
            Particle::DrippingLava => 9,
            Particle::FallingLava => 10,
            Particle::LandingLava => 11,
            Particle::DrippingWater => 12,
            Particle::FallingWater => 13,
            Particle::Dust { red: _, green: _, blue: _, scale: _ } => 14,
            Particle::DustColorTransition { from_red: _, from_green: _, from_blue: _, to_red: _, to_green: _, to_blue: _, scale: _ } => 15,
            Particle::Effect => 16,
            Particle::ElderGuardian => 17,
            Particle::EnchantedHit => 18,
            Particle::Enchant => 19,
            Particle::EndRod => 20,
            Particle::EntityEffect => 21,
            Particle::ExplosionEmitter => 22,
            Particle::Explosion => 23,
            Particle::Gust => 24,
            Particle::GustEmitter => 25,
            Particle::SonicBoom => 26,
            Particle::FallingDust { block: _ } => 27,
            Particle::Firework => 28,
            Particle::Fishing => 29,
            Particle::Flame => 30,
            Particle::CherryLeaves => 31,
            Particle::SculkSoul => 32,
            Particle::SculkCharge => 33,
            Particle::SculkChargePop => 34,
            Particle::SoulFireFlame => 35,
            Particle::Soul => 36,
            Particle::Flash => 37,
            Particle::HappyVillager => 38,
            Particle::Composter => 39,
            Particle::Heart => 40,
            Particle::InstantEffect => 41,
            Particle::Item { item: _, nbt: _ } => 42,
            Particle::Vibration { destination: _, arrival_in_ticks: _ } => 43,
            Particle::ItemSlime => 44,
            Particle::ItemSnowball => 45,
            Particle::LargeSmoke => 46,
            Particle::Lava => 47,
            Particle::Mycelium => 48,
            Particle::Note => 49,
            Particle::Poof => 50,
            Particle::Portal => 51,
            Particle::Rain => 52,
            Particle::Smoke => 53,
            Particle::WhiteSmoke => 54,
            Particle::Sneeze => 55,
            Particle::Spit => 56,
            Particle::SquidInk => 57,
            Particle::SweepAttack => 58,
            Particle::TotemOfUndying => 59,
            Particle::Underwater => 60,
            Particle::Splash => 61,
            Particle::Witch => 62,
            Particle::BubblePop => 63,
            Particle::CurrentDown => 64,
            Particle::BubbleColumnUp => 65,
            Particle::Nautilus => 66,
            Particle::Dolphin => 67,
            Particle::CampfireCosySmoke => 68,
            Particle::CampfireSignalSmoke => 69,
            Particle::DrippingHoney => 70,
            Particle::FallingHoney => 71,
            Particle::LandingHoney => 72,
            Particle::FallingNectar => 73,
            Particle::FallingSporeBlossom => 74,
            Particle::Ash => 75,
            Particle::CrimsonSpore => 76,
            Particle::WarpedSpore => 77,
            Particle::SporeBlossomAir => 78,
            Particle::DrippingObsidianTear => 79,
            Particle::FallingObsidianTear => 80,
            Particle::LandingObsidianTear => 81,
            Particle::ReversePortal => 82,
            Particle::WhiteAsh => 83,
            Particle::SmallFlame => 84,
            Particle::Snowflake => 85,
            Particle::DrippingDripstoneLava => 86,
            Particle::FallingDripstoneLava => 87,
            Particle::DrippingDripstoneWater => 88,
            Particle::FallingDripstoneWater => 89,
            Particle::GlowSquidInk => 90,
            Particle::Glow => 91,
            Particle::WaxOn => 92,
            Particle::WaxOff => 93,
            Particle::ElectricSpark => 94,
            Particle::Scrape => 95,
            Particle::Shriek { delay: _ } => 96,
            Particle::EggCrack => 97,
            Particle::DustPlume => 98,
            Particle::GustDust => 99,
            Particle::TrialSpawnerDetection => 100,
        }
    }
}